export type ForecastModelGuide = {
  name: string;
  provider: string;
  coverage: string;
  overview: string;
  operation: string;
  contribution: string;
  limit: string;
  sourceLabel: string;
  sourceUrl: string;
};

const guides: Record<string, ForecastModelGuide> = {
  arome: { name: "AROME", provider: "Météo-France", coverage: "France et zones voisines · courte échéance", overview: "AROME est un modèle régional à haute résolution utilisé pour décrire finement l’évolution de la météo près de la France.", operation: "Il calcule sur une grille l’évolution de la température, de l’humidité, du vent, des nuages et des précipitations.", contribution: "Il apporte un scénario détaillé de court terme. MeteoAI le compare aux autres sources et ne lui attribue jamais une priorité fixe.", limit: "Une sortie représente une maille de calcul, pas une station ni chaque rue. Elle reste une prévision et non une observation réelle.", sourceLabel: "Documentation AROME et ARPEGE", sourceUrl: "https://open-meteo.com/en/docs/meteofrance-api" },
  arpege: { name: "ARPEGE", provider: "Météo-France", coverage: "Europe et globe · horizon plus étendu", overview: "ARPEGE est le modèle à grande échelle de Météo-France. Sa couverture élargie complète l’information plus locale d’AROME.", operation: "Il calcule l’état de l’atmosphère sur un vaste domaine pour suivre les masses d’air, les fronts et les dépressions à plusieurs jours.", contribution: "Il offre un scénario Météo-France plus large. Sa part éventuelle dépend de la trace de fusion, du paramètre et des performances mesurées.", limit: "Sa grille est moins adaptée aux détails d’un microclimat qu’un modèle régional ou une station physique qualifiée.", sourceLabel: "Documentation AROME et ARPEGE", sourceUrl: "https://open-meteo.com/en/docs/meteofrance-api" },
  icon: { name: "ICON", provider: "Deutscher Wetterdienst (DWD)", coverage: "Globe · scénario indépendant pour l’Europe", overview: "ICON est le modèle global de prévision numérique du service météorologique allemand. Il s’appuie sur une grille icosaédrique couvrant le globe.", operation: "Il calcule notamment température, vent, humidité, nuages, pluie et neige sur ses mailles. Ces champs sont des moyennes de zone, non des mesures ponctuelles.", contribution: "Il apporte un regard indépendant. MeteoAI l’utilise seulement s’il est reçu et retenu dans la trace du créneau.", limit: "Les vallées, rues et microclimats plus petits que la maille ne sont pas entièrement résolus ; une station qualifiée reste nécessaire pour une observation locale.", sourceLabel: "Description officielle d’ICON par le DWD", sourceUrl: "https://www.dwd.de/EN/research/weatherforecasting/num_modelling/01_num_weather_prediction_modells/icon_description.html" },
  ecmwf: { name: "ECMWF", provider: "Centre européen pour les prévisions météorologiques à moyen terme", coverage: "Globe · moyen terme jusqu’à quinze jours", overview: "ECMWF désigne ici une prévision issue du centre européen, conçue pour suivre plusieurs scénarios météorologiques à moyen terme.", operation: "Ses produits d’ensemble explorent plusieurs évolutions plausibles. Lorsque les scénarios divergent, l’incertitude augmente.", contribution: "Il apporte une lecture de moyen terme. MeteoAI ne le déclare pas meilleur par principe : ses poids suivent les preuves disponibles par lieu, paramètre et horizon.", limit: "Une prévision ECMWF présente une possibilité calculée, non une certitude. Elle ne remplace ni la comparaison historique ni les observations physiques.", sourceLabel: "Prévisions à moyen terme ECMWF", sourceUrl: "https://www.ecmwf.int/en/forecasts/documentation-and-support/medium-range-forecasts" },
  gfs: { name: "GFS", provider: "NOAA / National Centers for Environmental Prediction (NCEP)", coverage: "Globe · aperçu à grande échelle", overview: "GFS est le système mondial de prévision du NCEP américain. Il produit notamment température, vent, précipitations et variables de surface.", operation: "Il fait évoluer un état initial de l’atmosphère et des surfaces à l’échelle du globe afin de suivre les grandes structures météo sur plusieurs jours.", contribution: "Il fournit un scénario global indépendant. MeteoAI ne le retient que lorsqu’une valeur exploitable est disponible pour le créneau et le paramètre concernés.", limit: "Sa vision globale ne constitue pas un relevé local : les détails fins restent soumis à la résolution du modèle et au contexte du lieu.", sourceLabel: "Description officielle du Global Forecast System", sourceUrl: "https://www.ncei.noaa.gov/products/weather-climate-models/global-forecast" },
  gem: { name: "GEM", provider: "Environment and Climate Change Canada (ECCC)", coverage: "Globe · prévision multi-échelle", overview: "GEM signifie Global Environmental Multiscale. C’est le système intégré de prévision et d’assimilation développé par le service canadien de l’environnement.", operation: "Il associe assimilation d’observations et modélisation numérique pour calculer l’évolution de l’atmosphère.", contribution: "Il ajoute un scénario issu d’un autre centre météorologique. Son éventuel poids reste calculé et traçable, jamais prédéfini par son nom.", limit: "Comme les autres modèles, GEM produit une estimation sur grille ; une prévision reçue ne constitue pas seule une validation locale.", sourceLabel: "Référentiel GEM d’ECCC", sourceUrl: "https://github.com/ECCC-ASTD-MRD/gem" },
  ukmet: { name: "UKMET", provider: "Met Office (Royaume-Uni)", coverage: "Globe et domaines régionaux · scénario indépendant", overview: "UKMET désigne dans MeteoAI une sortie du Met Office britannique, issue de la famille Unified Model utilisée pour la prévision numérique.", operation: "Le Unified Model représente les mouvements de l’atmosphère et des processus tels que nuages, convection, rayonnement et turbulence.", contribution: "Il apporte une autre hypothèse de calcul. MeteoAI l’emploie si le flux est disponible, puis le confronte aux autres sources et aux performances qualifiées.", limit: "Un modèle mondial ou régional ne décrit pas automatiquement chaque effet de relief, de littoral ou d’urbanisation au niveau d’une rue.", sourceLabel: "Présentation du Unified Model par le Met Office", sourceUrl: "https://www.metoffice.gov.uk/research/approach/modelling-systems/unified-model" },
  openmeteo: { name: "Open-Meteo", provider: "Open-Meteo", coverage: "Service d’accès et de traitement de sorties de modèles", overview: "Open-Meteo n’est pas un modèle physique unique. C’est un service qui met à disposition et traite les sorties de plusieurs modèles de services météorologiques nationaux.", operation: "Il récupère les cycles publiés, les prépare pour l’API et peut sélectionner un modèle adapté au lieu selon sa disponibilité et sa couverture.", contribution: "Lorsqu’Open-Meteo apparaît dans le relevé, MeteoAI trace un flux de prévision disponible. Cette étiquette ne signifie pas qu’un neuvième modèle indépendant a été inventé.", limit: "Le service d’accès ne remplace pas l’origine d’un modèle et ne doit jamais être confondu avec une observation réelle.", sourceLabel: "Disponibilité et mise à jour des modèles Open-Meteo", sourceUrl: "https://open-meteo.com/en/docs/model-updates" },
};

export function getForecastModelGuide(modelName: string): ForecastModelGuide {
  const key = modelName.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, "");
  if (key.includes("arome")) return guides.arome;
  if (key.includes("arpege")) return guides.arpege;
  if (key.includes("icon")) return guides.icon;
  if (key.includes("ecmwf") || key.includes("ifs")) return guides.ecmwf;
  if (key.includes("gfs")) return guides.gfs;
  if (key.includes("gem")) return guides.gem;
  if (key.includes("ukmet") || key.includes("ukmo") || key.includes("metoffice")) return guides.ukmet;
  return guides.openmeteo;
}
