CREATE TABLE `shadow_weather_phase8_metrics` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`periodKey` varchar(64) NOT NULL,
	`periodStart` bigint NOT NULL,
	`periodEnd` bigint NOT NULL,
	`locationKey` varchar(32) NOT NULL,
	`sourceKey` varchar(128) NOT NULL,
	`variable` varchar(48) NOT NULL,
	`phase3WindowKey` varchar(16) NOT NULL,
	`metricStatus` varchar(16) NOT NULL,
	`comparisonCount` int NOT NULL DEFAULT 0,
	`evaluatedDays` int NOT NULL DEFAULT 0,
	`physicalComparisonCount` int NOT NULL DEFAULT 0,
	`legacyComparisonCount` int NOT NULL DEFAULT 0,
	`mae` float,
	`rmse` float,
	`bias` float,
	`medianAbsoluteError` float,
	`rainHitRate` float,
	`rainHits` int NOT NULL DEFAULT 0,
	`rainMisses` int NOT NULL DEFAULT 0,
	`rainFalseAlarms` int NOT NULL DEFAULT 0,
	`windDirectionMeanAbsoluteError` float,
	`brierScore` float,
	`crps` float,
	`calibrationError` float,
	`metricAvailability` varchar(32) NOT NULL DEFAULT 'DETERMINISTIC_ONLY',
	`missingEvidence` json,
	`productionReadsEnabled` int NOT NULL DEFAULT 0,
	`shadowMode` int NOT NULL DEFAULT 1,
	`appliedToProduction` int NOT NULL DEFAULT 0,
	`evaluatedAt` bigint NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shadow_weather_phase8_metrics_id` PRIMARY KEY(`id`),
	CONSTRAINT `shadow_p8_metric_period_loc_src_var_win_uq` UNIQUE(`periodKey`,`locationKey`,`sourceKey`,`variable`,`phase3WindowKey`)
);
--> statement-breakpoint
CREATE INDEX `shadow_p8_metric_location_status_idx` ON `shadow_weather_phase8_metrics` (`locationKey`,`metricStatus`);--> statement-breakpoint
CREATE INDEX `shadow_p8_metric_source_variable_idx` ON `shadow_weather_phase8_metrics` (`sourceKey`,`variable`);--> statement-breakpoint
CREATE INDEX `shadow_p8_metric_applied_idx` ON `shadow_weather_phase8_metrics` (`appliedToProduction`);