import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

describe("Dashboard officiel avec contexte local", () => {
  it("préserve la température officielle tout en expliquant la moyenne station pondérée", () => {
    const source = readFileSync(new URL("./Dashboard.tsx", import.meta.url), "utf8");
    expect(source).not.toContain("Prévision officielle consolidée");
    expect(source).toContain("Moyenne locale pondérée");
    expect(source).toContain("Mes observations");
    expect(source).toContain('MeteoIcon name="wind_param" size={16}');
    expect(source).toContain('MeteoIcon name="humidity" size={16}');
    expect(source).toContain("Précipitations observées (mm)");
    expect(source).toContain("acceptsPersonalPrecipitation");
    expect(source).toContain("Très nuageux");
    expect(source).toContain("Quelques gouttes");
    expect(source).toContain("Forte pluie");
    expect(source).toContain("Enregistrer et comparer aux modèles");
    expect(source).toContain("personalObservations.submit.useMutation");
    expect(source).toContain("Données insuffisantes");
    expect(source).toContain("aria-expanded={isPersonalObservationOpen}");
    expect(source).toContain("Consulter l’historique complet");
    expect(source).toContain("Modifier mon observation");
    expect(source).toContain("Supprimer cette observation et recalculer la calibration");
    expect(source).toContain("Écart observé avec la prévision officielle");
    expect(source).toContain("hasMaterialLocalDelta");
    expect(source).toContain("La température principale reste la prévision au point du lieu.");
    expect(source).toContain("Contrôles calculés à cette requête : distance, fraîcheur, fiabilité, cohérence et altitude si renseignée.");
    expect(source).toContain("Couverture locale");
    expect(source).toContain("Stations contributrices");
    expect(source).toContain("localCoverageBands");
    expect(source).toContain("band.effectiveWeight");
    expect(source).toContain("Aucune station contributrice n’est disponible dans ce rayon.");
    expect(source).toContain("showAllLocalContributors");
    expect(source).toContain('localMode: loc.localMode ?? "standard"');
    expect(source).toContain("Tous les régimes");
    expect(source).not.toContain("Comment est calculée la fusion officielle ?");
    expect(source).toContain("Voir les 20 régimes");
    expect(source).not.toContain("max-h-72 overflow-y-auto");
    expect(source).toContain("weightRows");
    expect(source).toContain('role="progressbar"');
    expect(source).toContain("expandedRegimeIds");
    expect(source).toContain("aria-expanded={isExpanded}");
    expect(source).toContain('const needsLocalStations = localMode !== "standard"');
    expect(source).toContain("enabled: !!selectedLocation && needsLocalStations");
    expect(source).toContain("placeholderData: keepPreviousData");
    expect(source).toContain("gcTime: 10 * 60 * 1000");
    expect(source).toContain("Filtre local en cours…");
    expect(source).toContain('onClick={() => handleModeChange("standard")}');
    expect(source).toContain('aria-label="Fermer le contexte local et revenir au mode Officiel"');
    expect(source).toContain("Données horaires temporairement indisponibles.");
    expect(source).toContain("includeExtendedPeriods: false");
    expect(source).not.toContain("trpc.weather.getHourlyForecast.useQuery");
    expect(source).not.toContain('refetchOnReconnect: "always"');
    expect(source).not.toContain("refetchInterval: (query) => (query.state.data?.hours?.length ? 5 * 60 * 1000 : 30 * 1000)");
    expect(source).toContain('disabled={hourlyFetching}');
    expect(source).toContain('"Relance en cours…"');
    expect(source).toContain("const isLoading = officialLoading && hourlyLoading");
    expect(source).not.toContain("refetchHourlySnapshot()");
    expect(source).toContain("BackToTopButton");
    expect(source).not.toContain("Hondeghem, Nord");
    expect(source).not.toContain("MapPin");
    expect(source).toContain("candidate?.weights");
    expect(source).toContain("Régime de prévision dominant");
    const contextIndex = source.indexOf('aria-label="Mode de contexte local"');
    const heroRegimeIndex = source.indexOf("/* ── Regime badge ── */");
    const observationsIndex = source.indexOf('aria-labelledby="personal-observation-title"');
    expect(heroRegimeIndex).toBeLessThan(contextIndex);
    expect(observationsIndex).toBeGreaterThan(contextIndex);
    expect(source).not.toContain("{regime && (\n          <DominantRegimePanel");
    expect(source).toContain("Phénomène actuel");
    expect(source).toContain("Synthèse horaire · {regimeFreshnessLabel}");
    expect(source).toContain("whitespace-nowrap text-[15px] font-medium leading-tight");
    expect(source).toContain('nextRegimeChange.hour.replace(":00", "h")');
    expect(source).toContain('Évolution · {nextRegimeChange');
    expect(source).toContain('text-white">{displayedCondition');
    expect(source).toContain('text-white">{nextRegimeChange ? nextRegimeChange.label');
    expect(source).toContain("Confiance prévision");
    expect(source).toContain("isForecastInfoOpen");
    expect(source).toContain('aria-controls="forecast-information-panel"');
    expect(source).toContain('id="forecast-information-panel"');
    expect(source).toContain('Dialog open={isForecastInfoOpen} onOpenChange={setIsForecastInfoOpen}');
    expect(source).toContain('showCloseButton={false}');
    expect(source).toContain('max-h-[calc(100dvh-1rem)]');
    expect(source).toContain("Fermer les informations de prévision et de confiance");
    expect(source).toContain("Créneaux horaires indisponibles");
    expect(source).toContain("Dernière fusion quotidienne réelle");
    expect(source).toContain('isDailyFallback ? "Tendance quotidienne · " : "Phénomène actuel · "');
    expect(source).toContain('text-[15px] font-medium leading-tight text-slate-100/90 sm:text-lg');
    expect(source).toContain('formatDashboardCompactDate');
    expect(source).not.toContain('<WeatherStatusBadge dense tone="info"');
    expect(source).not.toContain('CalendarDays className="h-4 w-4 text-sky-300 sm:h-4.5 sm:w-4.5"');
    expect(source).toContain('text-lg font-bold tracking-tight text-slate-50 sm:text-xl');
    expect(source).toContain('space-y-2 px-3 pb-3 pt-1');
    expect(source).toContain('px-3 pb-3 pt-1 sm:p-6');
    expect(source).not.toContain('mb-0.5 flex justify-center sm:mb-3');
    expect(source).toContain('mb-1 flex justify-center sm:mb-1.5');
    expect(source).toContain("État du ciel</p>");
    expect(source).toContain("Phénomène actuel");
    expect(source).toContain('{panelDate}');
    expect(source).not.toContain('Tendance · {regimeSourceLabel}');
    expect(source).not.toContain('aria-label="Actualiser la météo maintenant"');
    expect(source).toContain('getExtremeTemperatureTone("max", maxTemperature)');
    expect(source).toContain('getExtremeTemperatureTone("min", minTemperature)');
    expect(source).toContain('maxTemperatureTone.container');
    expect(source).toContain('minTemperatureTone.container');
    expect(source).not.toContain("formatDashboardDate");
    expect(source).toContain("Tout développer");
    expect(source).toContain("Tout réduire");
    expect(source).toContain("overflow-visible rounded-[22px]");
    expect(source).toContain("dashboard-weather-page");
    expect(source).toContain("dashboard-sky-card");
    expect(source).not.toContain("Voir les prévisions détaillées");
    expect(source).not.toContain('href="/details"');
    expect(source).toContain("dashboardSkyImage");
    expect(source).toContain('temp: pf.forecast.tempCurrent ?? null');
    expect(source).toContain("const activeFavoriteWeather = {");
    expect(source).toContain("activeWeather={activeFavoriteWeather}");
    expect(source).not.toContain('alt="Paysage météo"');
    expect(source).toContain('w-[4.25rem] shrink-0 pt-0.5');
    expect(source).toContain('size={64} className="sm:hidden"');
    expect(source).toContain('size={80} className="hidden sm:block"');
    expect(source).toContain("getForecastCollectionReport");
    expect(source).toContain("Santé des collectes");
    expect(source).toContain("collection-health-panel");
    expect(source).toContain("Historique des 24 derniers passages horaires");
    expect(source).toContain("Une absence de station qualifiée n’est pas une erreur technique");
    expect(source).toContain("technicalFailureStreak");
    expect(source).toContain("hourlyCollectionHistory.length}/24");
    expect(source).toContain("refetchInterval: 15_000");
    expect(source).toContain("refetchIntervalInBackground: false");
    expect(source).toContain("refetchOnWindowFocus: true");
    expect(source).toContain("latestCollectionTraceKeyRef");
    expect(source).toContain("collectionUpdateNotice");
    expect(source).toContain("Actualisé · passage de");
    expect(source).toContain("Nouveau snapshot détecté");
    expect(source).toContain("ajouté à l’historique");
    expect(source).not.toContain("forecast-collection-title");
    const ventMaxIndex = source.indexOf("Vent max");
    const confidenceIndex = source.indexOf("Confiance prévision");
    expect(ventMaxIndex).toBeGreaterThan(-1);
    expect(confidenceIndex).toBeGreaterThan(ventMaxIndex);
  });
});
