import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

describe("Dashboard officiel avec contexte local", () => {
  it("préserve la température officielle tout en expliquant la moyenne station pondérée", () => {
    const source = readFileSync(new URL("./Dashboard.tsx", import.meta.url), "utf8");
    expect(source).not.toContain("Prévision officielle consolidée");
    expect(source).toContain("Moyenne locale pondérée");
    expect(source).toContain("Contrôles calculés à cette requête : distance, fraîcheur, fiabilité, cohérence et altitude si renseignée.");
    expect(source).toContain('localMode: loc.localMode ?? "standard"');
    expect(source).toContain("Tous les régimes");
    expect(source).not.toContain("Comment est calculée la fusion officielle ?");
    expect(source).toContain("Voir les 20 régimes");
    expect(source).not.toContain("max-h-72 overflow-y-auto");
    expect(source).toContain("weightRows");
    expect(source).toContain('role="progressbar"');
    expect(source).toContain("expandedRegimeIds");
    expect(source).toContain("aria-expanded={isExpanded}");
    expect(source).toContain('const needsLocalStations = localMode !== "standard"');
    expect(source).toContain("enabled: !!selectedLocation && needsLocalStations");
    expect(source).toContain("Données horaires temporairement indisponibles.");
    expect(source).toContain("trpc.weather.getHourlyForecast.useQuery");
    expect(source).toContain('refetchOnReconnect: "always"');
    expect(source).toContain("refetchInterval: (query) => (query.state.data?.hours?.length ? 5 * 60 * 1000 : 30 * 1000)");
    expect(source).toContain('disabled={hourlyFetching}');
    expect(source).toContain('"Relance en cours…"');
    expect(source).toContain("const isLoading = officialLoading && hourlyLoading");
    expect(source).toContain("refetchHourlySnapshot()");
    expect(source).toContain("BackToTopButton");
    expect(source).not.toContain("Hondeghem, Nord");
    expect(source).not.toContain("MapPin");
    expect(source).toContain("candidate?.weights");
    expect(source).toContain('text-base font-medium text-slate-100/90 sm:text-lg');
    expect(source).toContain('formatDashboardCompactDate');
    expect(source).not.toContain('<WeatherStatusBadge dense tone="info"');
    expect(source).toContain('CalendarDays className="h-4 w-4 text-sky-300"');
    expect(source).toContain('mb-2 flex justify-center sm:mb-3');
    expect(source).not.toContain('Tendance · {regimeSourceLabel}');
    expect(source).not.toContain('aria-label="Actualiser la météo maintenant"');
    expect(source).toContain('getExtremeTemperatureTone("max", maxTemperature)');
    expect(source).toContain('getExtremeTemperatureTone("min", minTemperature)');
    expect(source).toContain('maxTemperatureTone.container');
    expect(source).toContain('minTemperatureTone.container');
    expect(source).not.toContain("formatDashboardDate");
    expect(source).toContain("Tout développer");
    expect(source).toContain("Tout réduire");
    expect(source).toContain("overflow-visible rounded-[22px]");
    const ventMaxIndex = source.indexOf("Vent max");
    const confidenceIndex = source.indexOf("Confiance prévision");
    expect(ventMaxIndex).toBeGreaterThan(-1);
    expect(confidenceIndex).toBeGreaterThan(ventMaxIndex);
  });
});
