import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

describe("Dashboard avec état courant sourcé par variable", () => {
  it("préserve les prévisions et affiche la sélection physique ou le snapshot modèle avec sa provenance", () => {
    const source = readFileSync(new URL("./Dashboard.tsx", import.meta.url), "utf8");
    const metricDefinitions = readFileSync(new URL("../components/weather/ForecastMetricDefinitions.tsx", import.meta.url), "utf8");
    expect(source).not.toContain("Prévision officielle consolidée");
    expect(source).toContain("Moyenne locale pondérée");
    expect(source).toContain("<LocalModelContributionNotice");
    expect(source).toContain("<AltitudeCorrectionNotice correction={locationWeather.ultraLocal.altitudeCorrection}");
    expect(source).toContain('"alt. corrigée" : "brute"');
    expect(source).toContain("isPlaceholderData={locationWeatherIsPlaceholder}");
    expect(source).toContain("modelContribution={locationWeather.ultraLocal.modelContribution}");
    expect(source).toContain("modelWeight={locationWeather.ultraLocal.modelWeight}");
    expect(source).toContain("usesModelFallback={locationWeather.ultraLocal.usesModelFallback}");
    expect(source).toContain("Mes observations");
    expect(source).toContain('MeteoIcon name="wind_param" size={16}');
    expect(source).toContain('MeteoIcon name="humidity" size={16}');
    expect(source).toContain('status: "stored" | "no_station" | "failed" | "missing"');
    expect(source).toContain('label: "Créneau sans trace"');
    expect(source).toContain('label: "Archivé via reprise"');
    expect(source).toContain("missingSnapshotSlots");
    expect(source).toContain("getCollectionHealth");
    expect(source).toContain("formatCollectionDuration");
    expect(source).toContain("Précipitations observées (mm)");
    expect(source).toContain("acceptsPersonalPrecipitation");
    expect(source).toContain("Très nuageux");
    expect(source).toContain("Quelques gouttes");
    expect(source).toContain("Forte pluie");
    expect(source).toContain("Enregistrer et comparer aux modèles");
    expect(source).toContain("personalObservations.submit.useMutation");
    expect(source).toContain("Données insuffisantes");
    expect(source).toContain("PrecipitationConsensusChart");
    expect(source).toContain(
      "summary={isDailyFallback ? dailyFallback.precipitationConsensus : today?.precipitationConsensus}"
    );
    expect(source).toContain("aria-expanded={isPersonalObservationOpen}");
    expect(source).toContain("Consulter l’historique complet");
    expect(source).toContain("Modifier mon observation");
    expect(source).toContain("Supprimer cette observation et recalculer la calibration");
    expect(source).toContain("Écart du calcul local avec le snapshot du modèle");
    expect(source).toContain("hasMaterialLocalDelta");
    expect(source).toContain("getCurrentDashboardWeather.useQuery");
    expect(source).toContain("formatCurrentStateProvenance");
    expect(source).toContain("L’indicateur principal utilise les stations physiques retenues ou, champ par champ, le snapshot Open-Meteo");
    expect(source).toContain("Contrôles calculés à cette requête : distance, fraîcheur, fiabilité, cohérence et altitude seulement avec une référence explicite.");
    expect(source).toContain("Couverture locale");
    expect(source).toContain("Stations contributrices");
    expect(source).toContain("localCoverageBands");
    expect(source).toContain("band.effectiveWeight");
    expect(source).toContain("Aucune station contributrice n’est disponible dans ce rayon.");
    expect(source).toContain("showAllLocalContributors");
    expect(source).toContain('localMode: loc.localMode ?? "standard"');
    expect(source).toContain("Tous les régimes");
    expect(source).not.toContain("Comment est calculée la fusion officielle ?");
    expect(source).toContain("Voir les 20 régimes");
    expect(source).not.toContain("max-h-72 overflow-y-auto");
    expect(source).toContain("weightRows");
    expect(source).toContain('role="progressbar"');
    expect(source).toContain("expandedRegimeIds");
    expect(source).toContain("aria-expanded={isExpanded}");
    expect(source).toContain('const needsLocalStations = localMode !== "standard"');
    expect(source).toContain("enabled: !!selectedLocation && needsLocalStations");
    expect(source).toContain("placeholderData: keepPreviousData");
    expect(source).toContain("gcTime: 10 * 60 * 1000");
    expect(source).toContain("Filtre local en cours…");
    expect(source).toContain('onClick={() => handleModeChange("standard")}');
    expect(source).toContain('aria-label="Fermer le contexte local et revenir au mode Officiel"');
    expect(source).toContain("Données horaires temporairement indisponibles.");
    expect(source).toContain("includeExtendedPeriods: false");
    expect(source).toContain("const officialHours = officialForecast?.hours ?? []");
    expect(source).toContain("const hours = officialHours");
    expect(source).not.toContain("const officialHours: any[]");
    expect(source).not.toContain("personalizedByHour");
    expect(source).toContain("elle reste séparée de la série horaire officielle");
    expect(source).not.toContain("trpc.weather.getHourlyForecast.useQuery");
    expect(source).not.toContain('refetchOnReconnect: "always"');
    expect(source).not.toContain("refetchInterval: (query) => (query.state.data?.hours?.length ? 5 * 60 * 1000 : 30 * 1000)");
    expect(source).toContain('disabled={hourlyFetching}');
    expect(source).toContain('"Relance en cours…"');
    expect(source).toContain("const isLoading = officialLoading && hourlyLoading");
    expect(source).not.toContain("refetchHourlySnapshot()");
    expect(source).toContain("BackToTopButton");
    expect(source).not.toContain("Hondeghem, Nord");
    expect(source).not.toContain("MapPin");
    expect(source).toContain("candidate?.weights");
    expect(source).toContain("Régime de prévision dominant");
    const contextIndex = source.indexOf('aria-label="Mode de contexte local"');
    const heroRegimeIndex = source.indexOf("/* ── Regime badge ── */");
    const observationsIndex = source.indexOf('aria-labelledby="personal-observation-title"');
    expect(heroRegimeIndex).toBeLessThan(contextIndex);
    expect(observationsIndex).toBeGreaterThan(contextIndex);
    expect(source).not.toContain("{regime && (\n          <DominantRegimePanel");
    expect(source).toContain("currentSnapshot?.condition");
    expect(source).toContain("{regimeSourceLabel} · {regimeFreshnessLabel}");
    expect(source).not.toContain("Synthèse horaire");
    expect(source).toContain("Observations actuelles");
    expect(source).toContain("Prévisions du jour");
    expect(source).toContain("Direction · {formatCurrentStateProvenance(windDirectionField");
    expect(source).toContain("WindRose direction={windDir} />");
    expect(source).not.toContain("speed={windSpeed}");
    expect(source).toContain("title={currentStateFieldTitle(windSpeedField, currentSnapshot?.capturedAt)}");
    expect(source).toContain("formatDashboardNumber(currentHumidity)");
    expect(source).toContain("getRegimeProvenancePresentation({");
    expect(source).not.toContain("officialDataUpdatedAt");
    expect(source).toContain("whitespace-nowrap text-[15px] font-medium leading-tight");
    expect(source).toContain('nextRegimeChange.hour.replace(":00", "h")');
    expect(source).toContain('Évolution · {nextRegimeChange');
    expect(source).toContain('text-white">{displayedCondition');
    expect(source).toContain('text-white">{nextRegimeChange ? nextRegimeChange.label');
    expect(source).not.toContain("Confiance prévision");
    expect(source).toContain("Accord inter-modèles");
    expect(source).toContain("accord brut, pas fiabilité");
    expect(source).toContain("σ population");
    expect(source).toContain("incertitude statistique non mesurée");
    expect(metricDefinitions).toContain("Couverture et qualité physiques");
    expect(metricDefinitions).toContain("Incertitude statistique</strong> : non mesurée dans cette vue");
    expect(metricDefinitions).toContain("Fiabilité historique");
    expect(source).toContain("jour demandé");
    expect(source).toContain("heure de run modèle non archivée");
    expect(source).toContain("isForecastInfoOpen");
    expect(source).toContain('aria-controls="forecast-information-panel"');
    expect(source).toContain('id="forecast-information-panel"');
    expect(source).toContain('Dialog open={isForecastInfoOpen} onOpenChange={setIsForecastInfoOpen}');
    expect(source).toContain('showCloseButton={false}');
    expect(source).toContain('max-h-[calc(100dvh-1rem)]');
    expect(source).toContain("Fermer les informations de prévision et d’accord inter-modèles");
    expect(source).toContain("Créneaux horaires indisponibles");
    expect(source).toContain("Dernière fusion quotidienne réelle");
    expect(source).toContain('isDailyFallback ? "Tendance quotidienne · " : currentSnapshot || hasAvailableCurrentState ? "État actuel · " : "État courant indisponible · "');
    expect(source).toContain('text-[15px] font-medium leading-tight text-slate-100/90 sm:text-lg');
    expect(source).toContain('formatDashboardCompactDate');
    expect(source).not.toContain('<WeatherStatusBadge dense tone="info"');
    expect(source).not.toContain('CalendarDays className="h-4 w-4 text-sky-300 sm:h-4.5 sm:w-4.5"');
    expect(source).toContain('text-lg font-bold tracking-tight text-slate-50 sm:text-xl');
    expect(source).toContain('space-y-2 px-1 pb-3 pt-[max(env(safe-area-inset-top),0.25rem)]');
    expect(source).toContain('min-h-dvh w-full overflow-x-clip bg-background');
    expect(source).toContain('w-full min-w-0 max-w-none space-y-2');
    expect(source).toContain('sm:max-w-2xl');
    expect(source).toContain('px-3 pb-3 pt-1 sm:p-6');
    expect(source).not.toContain('mb-0.5 flex justify-center sm:mb-3');
    expect(source).toContain('mb-1 flex justify-center sm:mb-1.5');
    expect(source).toContain("État du ciel</p>");
    expect(source).toContain("Open-Meteo");
    expect(source).toContain('dir == null ? "—" : cardinalDir(dir)');
    expect(source).toContain("Précipitations actuelles");
    expect(source).toContain("Pression locale");
    expect(source).toContain("hasCurrentDashboardFields ? currentNumber(temperatureField) : officialSnapshotTemp");
    expect(source).toContain("Cumul station non comparable");
    expect(source).toContain("Références source non comparables");
    expect(source).toContain('{panelDate}');
    expect(source).not.toContain('Tendance · {regimeSourceLabel}');
    expect(source).not.toContain('aria-label="Actualiser la météo maintenant"');
    expect(source).toContain('getExtremeTemperatureTone("max", maxTemperature)');
    expect(source).toContain('getExtremeTemperatureTone("min", minTemperature)');
    expect(source).toContain('maxTemperatureTone.container');
    expect(source).toContain('minTemperatureTone.container');
    expect(source).not.toContain("formatDashboardDate");
    expect(source).toContain("Tout développer");
    expect(source).toContain("Tout réduire");
    expect(source).toContain("overflow-visible rounded-[22px]");
    expect(source).toContain("dashboard-sky-card");
    expect(source).toContain('<div className="dashboard-sky-card relative overflow-hidden');
    expect(source).toContain("dashboard-sky-image");
    expect(source).not.toContain("Voir les prévisions détaillées");
    expect(source).not.toContain('href="/details"');
    expect(source).toContain("dashboardSkyImage");
    expect(source).toContain('temp: pf.forecast.tempCurrent ?? null');
    expect(source).toContain("const activeFavoriteWeather = {");
    expect(source).toContain("activeWeather={activeFavoriteWeather}");
    expect(source).not.toContain('alt="Paysage météo"');
    expect(source).toContain('w-[4.75rem] shrink-0 pt-0.5');
    expect(source).toContain('size={64}');
    expect(source.match(/<MeteoIcon name=\{getIconNameFromCondition\(displayedCondition\)\}/g)?.length).toBe(1);
    expect(source).toContain("getForecastCollectionReport");
    expect(source).toContain("getCollectionHealth");
    expect(source).toContain("formatCollectionDuration");
    expect(source).toContain("formatCollectionTimestamp");
    expect(source).toContain("Europe/Paris");
    expect(source).toContain("lastForecastRun");
    expect(source).toContain("recentForecastRuns");
    expect(source).toContain("Deux derniers lots de prévisions");
    expect(source).toContain("dailyModelsCollected}/{run.dailyModelsExpected");
    expect(source).toContain("hourlyModelsCollected}/{run.hourlyModelsExpected");
    expect(source).toContain("nextForecastRun");
    expect(source).toContain("Détails&nbsp;→");
    expect(source).toContain("Santé des collectes");
    expect(source).toContain("collection-health-panel");
    expect(source).toContain("Historique des 24 derniers créneaux horaires");
    expect(source).toContain("Une absence de station qualifiée n’est pas une erreur technique");
    expect(source).toContain("technicalFailureStreak");
    expect(source).toContain("countArchivedSnapshotSlots(hourlyCollectionHistory)");
    expect(source).toContain("archivedSnapshotSlots}/${hourlyCollectionHistory.length}");
    expect(source).toContain("créneaux archivés");
    expect(source).toContain("refetchInterval: 15_000");
    expect(source).toContain("refetchIntervalInBackground: false");
    expect(source).toContain("refetchOnWindowFocus: true");
    expect(source).toContain("latestCollectionTraceKeyRef");
    expect(source).toContain("collectionUpdateNotice");
    expect(source).toContain("Trace · {hourlyCollectionMoment(collectionUpdateNotice)}");
    expect(source).toContain("Trace horaire mise à jour");
    expect(source).toContain("latestHourlyCollection.status !== \"missing\"");
    expect(source).not.toContain("forecast-collection-title");
    const ventMaxIndex = source.indexOf("Vent max");
    const agreementIndex = source.indexOf("Accord inter-modèles");
    expect(ventMaxIndex).toBeGreaterThan(-1);
    expect(agreementIndex).toBeGreaterThan(ventMaxIndex);
  });
});
