import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const source = readFileSync(new URL("./WeatherDetails.tsx", import.meta.url), "utf8");

describe("page Prévisions détaillées", () => {
  it("réutilise les surfaces et contrôles visuels MeteoAI", () => {
    expect(source).toContain('import { MeteoSurface } from "@/components/weather/MeteoSurface"');
    expect(source).toContain('import { BackToTopButton } from "@/components/BackToTopButton"');
    expect(source).toContain('tone="default"');
    expect(source).toContain("weather-chart-3d");
    expect(source).toContain("<BackToTopButton />");
    expect(source).toContain("w-[160px]");
    expect(source).toContain("hours.length * 170");
    expect(source).toContain("text-[36px] font-semibold leading-none");
    expect(source).toContain("Détails par heure");
    expect(source).toContain('aria-label="Détails horaires défilables"');
    expect(source).toContain("hours.length * 186");
    expect(source).toContain("w-[174px]");
    expect(source).toContain("Temp. · ressenti · vent · pluie · humidité · pression");
    expect(source).toContain("chartScrollRef");
    expect(source).toContain("detailScrollRef");
    expect(source).toContain("detailCardStride = 186");
    expect(source).toContain('scrollTo({ left: detailTargetLeft, behavior: "auto" })');
    expect(source).toContain("syncDetailScroll");
    expect(source).toContain("syncChartScroll");
    expect(source).toContain("detailTargetLeft = progress * detailScrollableWidth");
    expect(source).toContain("chartTargetLeft = progress * chartScrollableWidth");
    expect(source).toContain("onScroll={syncDetailScroll}");
    expect(source).toContain("onScroll={syncChartScroll}");
    expect(source).toContain("const chartTop = 36");
    expect(source).toContain("chartBottom = chartH - 8");
    expect(source).not.toContain('paintOrder="stroke"');
    expect(source).toContain("chartH + 42");
    expect(source).toContain("MAINTENANT");
    expect(source).toContain(">Maintenant</text>");
    expect(source).toContain("hourlyCardStride = 170");
    expect(source).toContain('rail.scrollTo({ left: targetLeft, behavior: "auto" })');
    expect(source).toContain("rgba(77,105,132,0.38)");
    expect(source).toContain("rgba(44,128,181,0.48)");
    expect(source).toContain("HourlyMetric");
    expect(source).toContain("hourlyTemperatureTone(h.temp)");
    expect(source).toContain('return "text-amber-200"');
    expect(source).toContain('return "text-orange-300"');
    expect(source).toContain("Déroulé temporel");
    expect(source).not.toContain("Prévision officielle");
    expect(source).toContain('y={chartH + 58} textAnchor="middle"');
    expect(source).toContain('fontSize="14"');
    expect(source).toContain('fontSize={i === currentIdx ? "13" : "12"}');
  });
});
