import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

describe("Weather AI Lab — transparence de fusion", () => {
  it("centralise la méthode et les sources de fusion hors du Dashboard", () => {
    const source = readFileSync(new URL("./WeatherAILab.tsx", import.meta.url), "utf8");
    expect(source).toContain("Simulation de la fusion");
    expect(source).toContain("Pondération finale");
    expect(source).toContain("Poids réellement appliqués par paramètre");
    expect(source).toContain('key: "humidity"');
    expect(source).toContain("Aucune trace disponible.");
    expect(source).toContain("Résultat officiel");
    expect(source).toContain("Données exploitables");
    expect(source).not.toContain("Régime de prévision dominant");
    expect(source).not.toContain("Le Dashboard indique séparément le phénomène immédiat");
    expect(source).toContain("Lexique, méthode et sources");
    expect(source).toContain("AI_LAB_GLOSSARY");
    expect(source).toContain("MeteoAI en quelques mots");
    expect(source).toContain("Comparer avant de privilégier");
    expect(source).toContain("Apprendre sans réécrire le passé");
    expect(source).toContain("Expliquer les limites");
    expect(source).toContain("Confiance");
    expect(source).toContain("Poids du régime, en clair");
    expect(source).toContain("Exemple : Ciel couvert");
    expect(source).toContain("ne veut pas dire 30 % de nuages");
    expect(source).toContain("Poids moyen d’un modèle");
    expect(source).toContain("Pourquoi plusieurs flux ont le même poids moyen");
    expect(source).toContain("Ce n’est ni une note, ni une chance qu’il ait raison");
    expect(source).toContain("ce n’est pas un classement ni une probabilité");
    expect(source).toContain("AI_LAB_GLOSSARY_EXAMPLES");
    expect(source).toContain("Sources appliquées par paramètre");
    expect(source).toContain("AROME peut aider pour la température");
    expect(source).toContain("Si les modèles prévoient entre 19 et 20 °C");
    expect(source).toContain("Exemple ·");
    expect(source).not.toContain("Exemple simple ·");
    expect(source).toContain("Fermer le Lexique");
    expect(source).toContain("setIsOpen(false)");
    expect(source).toContain("Stabilité des modèles");
    expect(source).toContain("Données insuffisantes / —");
    expect(source).toContain("group-open:rotate-180");
    expect(source).toContain("Horizon de prévision");
    expect(source).toContain("MAE");
    expect(source).toContain("RMSE");
    expect(source).toContain("Seuils de décision");
    expect(source).toContain("Observations réelles et analyse nocturne");
    expect(source).toContain("Prévisions de référence · 05 h 00");
    expect(source).toContain("Analyse de nuit · 00 h 30");
    expect(source).toContain("Journée qualifiée");
    expect(source).toContain("Comparaison et scores");
    expect(source).toContain("ce n’est donc pas un score immédiat affiché au soir");
    expect(source).toContain("Correction de biais");
    expect(source).toContain("Maille et microclimat");
    expect(source).toContain("Sources, provenance et cartes");
    expect(source).toContain("Netatmo Weather API");
    expect(source).toContain("Google Maps JavaScript API");
    expect(source).toContain("Astronomy Engine");
    expect(source).toContain("Visibilité d’éclipse");
    expect(source).toContain("Ces modèles sont archivés pour une validation historique");
    expect(source).toContain("gain de fiabilité n’est pas mesuré");
    expect(source).toContain("Calcul de l’indicateur");
    expect(source).toContain("40 % accord des modèles");
    expect(source).toContain("60 % de stabilité des températures maximales");
    expect(source).toContain("poids final strictement positif");
    expect(source).toContain("PopoverClose");
    expect(source).toContain("h-6 w-6");
    expect(source).toContain("Simulation de la fusion");
    expect(source).toContain("Snapshot retenu");
    expect(source).toContain("Collecte des flux");
    expect(source).toContain("Pondération finale");
    expect(source).toContain("Résultat officiel");
    expect(source).not.toContain("Résultat final · contexte des stations locales");
    expect(source).not.toContain("Aucune station physique locale active");
    expect(source).toContain("grid-cols-[minmax(90px,0.72fr)_minmax(0,1.5fr)]");
    expect(source).toContain("before:bg-sky-300/20");
    expect(source).toContain("Étape {activeStep + 1} sur {steps.length}");
    expect(source).toContain("Branche complémentaire · Stations locales");
    expect(source).toContain("Recherche locale");
    expect(source).toContain("Filtre physique");
    expect(source).toContain("Synthèse locale");
    expect(source).toContain("Preuve qualifiée");
    expect(source).toContain("getEvidenceStatus");
    expect(source).toContain("getForecastCollectionReport");
    expect(source).toContain("CollectionOperations");
    expect(source).toContain("Derniers succès de collecte");
    expect(source).toContain("formatCollectionTimestamp");
    expect(source).toContain("Mis à jour le ${formatCollectionTimestamp(collection.collectedAt)}");
    expect(source).toContain("Créneaux sans station qualifiée");
    expect(source).toContain("lastForecastSuccess");
    expect(source).toContain("lastPhysicalCollection");
    expect(source).toContain("noQualifiedStationSlots");
    expect(source).toContain("scheduleCoverage");
    expect(source).toContain("staleTime: 2 * 60_000");
    expect(source).toContain("staleTime: 5 * 60_000");
    expect(source).toContain("Prévisions · 7 modèles + 1 agrégateur");
    expect(source).toContain("Collecte prévue à {forecastCollectionReport?.scheduledAt");
    expect(source).toContain("ce n’est pas une confirmation du passage de 05:00 du jour en cours");
    expect(source).toContain("Stations météorologiques ·");
    expect(source).toContain("leurs relevés physiques sont collectés par un flux horaire distinct");
    expect(source).toContain("expectedForecastModels.map");
    expect(source).toContain("Q = prévision quotidienne archivée ; H = prévision horaire archivée");
    expect(source).toContain("Open-Meteo Best Match est un agrégateur, pas un modèle indépendant");
    expect(source).toContain("forecastNamedModelCount");
    expect(source).toContain("forecastAggregatorCount");
    expect(source).toContain("Agrégateur Best Match");
    expect(source).toContain("getForecastModelGuide");
    expect(source).toContain("Ouvrir la fiche du flux");
    expect(source).toContain("Comprendre le modèle");
    expect(source).toContain("Comment il fonctionne");
    expect(source).toContain("Ce que MeteoAI en fait");
    expect(source).toContain("Limite à connaître");
    expect(source).toContain("Touchez un nom pour connaître son rôle");
    expect(source).toContain("ForecastFlowStatusLegend");
    expect(source).toContain("ForecastFlowStatusBadge");
    expect(source).toContain("Statut opérationnel de tous les flux de prévision");
    expect(source).toContain('operationalStatus?.status ?? "FAILED"');
    expect(source).toContain('import { BackToTopButton } from "@/components/BackToTopButton"');
    expect(source).toContain("<BackToTopButton />");
    expect(source).toContain('className="order-[-1] grid grid-cols-3 gap-2"');
    expect(source).toContain('className="order-[-2] flex items-center justify-between gap-2"');
    expect(source).toContain("getShadowDataHubReport");
    expect(source).toContain('enabled: user?.role === "admin"');
    expect(source).toContain("Data Hub canonique shadow");
    expect(source).toContain("Production protégée");
    expect(source).toContain("aucune valeur de ce Data Hub n’alimente les prévisions, scores ou poids");
    expect(source).toContain("Observation P1.6");
    expect(source).toContain("shadowDataHubReport.observation.elapsedDays");
    expect(source).toContain("shadowDataHubReport.observation.remainingDays");
    expect(source).toContain("Appliqué à production");
    expect(source).toContain("ProviderRunEvidencePanel");
    expect(source).toContain("shadowDataHubReport && <ProviderRunEvidencePanel");
    expect(source).toContain("Phase2SourceClassificationPanel");
    expect(source).toContain("Phase3HorizonHierarchyPanel");
    expect(source).toContain("Phase4NormalizationPanel");
    expect(source).toContain("Phase5QualityControlPanel");
    expect(source).toContain("Phase6SmartFusionPanel");
    expect(source).toContain("Phase7LocalPerformancePanel");
    expect(source).toContain('user?.role === "admin" && shadowDataHubReport?.phase2Classification');
    expect(source).toContain('user?.role === "admin" && shadowDataHubReport?.phase3HorizonHierarchy');
    expect(source).toContain('user?.role === "admin" && shadowDataHubReport?.phase4Normalization');
    expect(source).toContain('user?.role === "admin" && shadowDataHubReport?.phase5QualityControl');
    expect(source).toContain('user?.role === "admin" && shadowDataHubReport?.phase6Fusion');
    expect(source).toContain('user?.role === "admin" && shadowDataHubReport?.phase7LocalPerformance');
  });

  it("présente explicitement la dernière fusion archivée sans la confondre avec la prévision actuelle", () => {
    const source = readFileSync(new URL("./WeatherAILab.tsx", import.meta.url), "utf8");
    expect(source).toContain("snapshotStatus");
    expect(source).not.toContain("Dernière fusion archivée");
    expect(source).toContain("photo enregistrée à un moment précis");
    expect(source).toContain("photo conservée des modèles reçus");
    expect(source).not.toContain("Débuter dans l’AI Lab");
    expect(source).not.toContain("Lire l’écran en trois gestes");
    expect(source).not.toContain("SnapshotPhotoGuide");
    expect(source).not.toContain(">Actualiser</button>");
    expect(source).toContain('"Relancer"');
  });

  it("présente les résultats quotidiens et horaires séparément et rafraîchit le Dashboard du même lieu", () => {
    const source = readFileSync(new URL("./WeatherAILab.tsx", import.meta.url), "utf8");
    expect(source).toContain("refreshManualFusion");
    expect(source).toContain("Relancer");
    expect(source).toContain("manualRefreshGranularity(\"Quotidien\"");
    expect(source).toContain("manualRefreshGranularity(\"Horaire\"");
    expect(source).toContain("getDashboard.invalidate(coordinates)");
    expect(source).toContain("getDetailedForecast.invalidate(detailedForecastInput)");
    expect(source).toContain("getDashboard.fetch(coordinates)");
    expect(source).toContain("La relance n’écrit ni le point météo courant ni les observations, qui restent alimentés séparément");
    expect(source).toContain("Les compteurs du batch planifié de 05:00 ne sont pas modifiés");
    expect(source).toContain("Une fusion récente existe déjà");
  });
});
