import { trpc } from "@/lib/trpc";
import { useLocation } from "@/contexts/LocationContext";
import { Link } from "wouter";
import { AlertTriangle, BarChart3, ClipboardCheck, Database, FlaskConical, MapPin, RefreshCw, ShieldCheck, Zap } from "lucide-react";
import { MeteoSurface } from "@/components/weather/MeteoSurface";
import { getValidationModelSource } from "@/lib/validationModelSource";
import { WeatherStatusBadge } from "@/components/weather/WeatherStatusBadge";

function Stat({ label, value, tone = "text-slate-100" }: { label: string; value: string; tone?: string }) {
  return <MeteoSurface tone="lab" className="rounded-xl bg-black/20 px-2 py-2.5 text-center"><p className={`text-xl font-bold ${tone}`}>{value}</p><p className="mt-0.5 text-[10px] uppercase tracking-wide text-slate-500">{label}</p></MeteoSurface>;
}

function Divergence({ label, value, max, unit, color }: { label: string; value: number; max: number; unit: string; color: string }) {
  const ratio = Math.min(100, Math.round((value / Math.max(max, 1)) * 100));
  const level = ratio < 30 ? "Faible" : ratio < 60 ? "Modéré" : "Élevé";
  const tone = ratio < 30 ? "text-emerald-400" : ratio < 60 ? "text-amber-300" : "text-red-300";
  return <div className="space-y-1"><div className="flex justify-between gap-2 text-xs"><span className="text-slate-400">{label}</span><span className="font-semibold text-slate-200">{value} {unit} <span className={tone}>· {level}</span></span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${color}`} style={{ width: `${ratio}%` }} /></div></div>;
}

export default function WeatherAILab() {
  const { activeLocation } = useLocation();
  const input = activeLocation ? { lat: activeLocation.lat, lon: activeLocation.lon } : undefined;
  const { data, isLoading, isFetching, error, refetch } = trpc.weather.getAILab.useQuery(input, { staleTime: 60_000, refetchOnWindowFocus: true });

  if (isLoading) return <div className="mx-auto max-w-2xl space-y-3 px-3 py-4">{Array.from({ length: 5 }).map((_, index) => <div key={index} className="h-28 animate-pulse rounded-2xl bg-slate-800" />)}</div>;
  if (error || !data) return <div className="mx-auto max-w-2xl px-3 py-5"><div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-5 text-center"><AlertTriangle className="mx-auto h-6 w-6 text-red-300" /><p className="mt-2 text-sm text-red-100">Impossible de charger la traçabilité de cette prévision.</p><button onClick={() => refetch()} className="mt-3 text-xs font-semibold text-red-200 underline">Réessayer</button></div></div>;

  const hasTrace = data.appliedModelWeights.length > 0;
  const hasSnapshot = Boolean(data.calculatedAt);
  const confidenceTone = data.confidenceScore >= 80 ? "text-emerald-300" : data.confidenceScore >= 60 ? "text-amber-300" : "text-red-300";
  const updatedAt = data.calculatedAt ? new Date(data.calculatedAt).toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Paris" }) : null;
  const collection = data.latestStationCollection;
  const validationSource = getValidationModelSource(data.sources);
  const fusionParameters = [
    { key: "temperature", label: "Température", tone: "text-orange-200", background: "bg-orange-400/10" },
    { key: "precipitation", label: "Précipitations", tone: "text-blue-200", background: "bg-blue-400/10" },
    { key: "wind", label: "Vent", tone: "text-cyan-200", background: "bg-cyan-400/10" },
  ].map(({ key, label, tone, background }) => ({
    key,
    label,
    tone,
    background,
    sources: (((data.trace as any)?.parameterSources?.[key] ?? []) as any[])
      .filter((source) => source.type === "model" && Number.isFinite(source.finalWeight) && source.finalWeight > 0),
  }));

  return <main className="weather-page-sky min-h-screen mx-auto max-w-2xl space-y-3 px-3 py-3 pb-24 sm:px-6 sm:py-6">
    <header className="flex items-center justify-between gap-2">
      <div className="flex min-w-0 items-center gap-2"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-blue-500/15"><FlaskConical className="h-5 w-5 text-blue-300" /></div><div className="min-w-0"><h1 className="text-base font-bold text-slate-100">AI Lab · traçabilité</h1><p className="truncate text-xs text-slate-500">{activeLocation?.name ?? "Lieu actif"}{updatedAt ? ` · calcul à ${updatedAt}` : " · snapshot indisponible"}</p></div></div>
      <button onClick={() => refetch()} disabled={isFetching} className="inline-flex min-h-11 shrink-0 items-center gap-1 rounded-lg border border-blue-400/30 bg-blue-400/10 px-3 text-xs font-semibold text-blue-200 disabled:opacity-60"><RefreshCw className={`h-3.5 w-3.5 ${isFetching ? "animate-spin" : ""}`} />Actualiser</button>
    </header>

    <section className="grid grid-cols-3 gap-2"><Stat label="Confiance prévision" value={hasSnapshot ? `${Math.round(data.confidenceScore)}%` : "—"} tone={hasSnapshot ? confidenceTone : "text-slate-500"} /><Stat label="Stabilité modèles" value={hasSnapshot ? `${Math.round(data.stabilityScore)}%` : "—"} tone={hasSnapshot ? "text-sky-300" : "text-slate-500"} /><Stat label="Modèles appliqués" value={hasTrace ? String(data.modelsUsed) : "—"} tone={hasTrace ? "text-violet-300" : "text-slate-500"} /></section>

    <section className="rounded-2xl border border-sky-400/25 bg-gradient-to-br from-sky-500/[0.08] via-[#0d131d] to-[#0d131d] p-4"><div className="flex items-start gap-2"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-400" /><div><h2 className="text-sm font-semibold text-slate-100">Fusion officielle actuelle</h2><p className="mt-1 text-xs leading-relaxed text-slate-400">{hasTrace ? "Cette section explique les mêmes pondérations que celles utilisées pour la prévision officielle actuelle." : "Aucune trace de pondération n’est disponible pour ce snapshot. Aucun modèle n’est présenté comme dominant."}</p></div></div>
      {hasTrace && <><div className="mt-3 grid grid-cols-3 gap-1.5 text-center"><div className="rounded-xl border border-slate-700 bg-black/20 px-2 py-2"><p className="text-[10px] uppercase tracking-wide text-slate-500">Modèle principal</p><p className="mt-0.5 text-sm font-bold text-sky-200">{data.modelIndicator?.primaryModel ?? "—"}</p></div><div className="rounded-xl border border-slate-700 bg-black/20 px-2 py-2"><p className="text-[10px] uppercase tracking-wide text-slate-500">Poids appliqué</p><p className="mt-0.5 text-sm font-bold text-blue-200">{data.modelIndicator?.primaryWeight == null ? "—" : `${Math.round(data.modelIndicator.primaryWeight * 100)}%`}</p></div><div className="rounded-xl border border-slate-700 bg-black/20 px-2 py-2"><p className="text-[10px] uppercase tracking-wide text-slate-500">Contributeurs</p><p className="mt-0.5 text-sm font-bold text-violet-200">{data.modelIndicator?.modelCount ?? 0}</p></div></div><div className="mt-3 rounded-xl border border-sky-400/15 bg-slate-950/35 p-2.5"><p className="text-[10px] font-semibold uppercase tracking-wide text-sky-200">Méthode de fusion</p><p className="mt-1 text-xs leading-relaxed text-slate-300">{(data.trace as any)?.method ?? "Trace détaillée indisponible."} Le pourcentage affiché est un poids appliqué à la prévision, jamais une mesure de station.</p></div>{fusionParameters.some((parameter) => parameter.sources.length > 0) && <div className="mt-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Sources appliquées par paramètre</p><div className="mt-1.5 grid gap-1.5">{fusionParameters.filter((parameter) => parameter.sources.length > 0).map((parameter) => <div key={parameter.key} className={`rounded-lg ${parameter.background} px-2.5 py-2 text-[11px]`}><span className={`font-semibold ${parameter.tone}`}>{parameter.label}</span><span className="text-slate-300"> · {parameter.sources.map((source) => `${source.name} ${Math.round(source.finalWeight * 100)}%`).join(" · ")}</span></div>)}</div></div>}<div className="mt-3 space-y-2">{data.appliedModelWeights.map((model) => <div key={model.name} className="rounded-xl border border-slate-800 bg-black/15 p-2.5"><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold text-slate-100">{model.name}</span><span className="text-xs font-semibold text-blue-300">moyenne {Math.round(model.averageWeight * 100)}%</span></div><div className="mt-2 grid grid-cols-3 gap-1.5 text-center text-[10px]"><span className="rounded-md bg-orange-400/10 py-1 text-orange-200">T° {model.temperature == null ? "—" : `${Math.round(model.temperature * 100)}%`}</span><span className="rounded-md bg-blue-400/10 py-1 text-blue-200">Pluie {model.precipitation == null ? "—" : `${Math.round(model.precipitation * 100)}%`}</span><span className="rounded-md bg-cyan-400/10 py-1 text-cyan-200">Vent {model.wind == null ? "—" : `${Math.round(model.wind * 100)}%`}</span></div></div>)}</div></>}
    </section>

    {validationSource && <section className="rounded-2xl border border-dashed border-violet-400/35 bg-violet-400/[0.045] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><FlaskConical className="mt-0.5 h-5 w-5 shrink-0 text-violet-300" /><div><h2 className="text-sm font-semibold text-slate-100">Modèles en validation</h2><p className="mt-1 text-xs leading-relaxed text-slate-400">Collectés séparément à 05h00 lorsqu’ils sont disponibles. Ils n’influencent ni la prévision officielle, ni les poids, ni les compteurs des modèles actifs.</p></div></div></div><WeatherStatusBadge compact className="w-[104px]" tone="lab" label="Validation" value="Hors fusion" description="Ces modèles sont archivés et comparés séparément. Ils ne participent pas à la prévision officielle tant qu’un gain de fiabilité n’est pas démontré." /></div><div className="mt-3 flex flex-wrap gap-1.5">{validationSource.models.map((model) => <WeatherStatusBadge key={model} compact tone="lab" label={model} description="Modèle candidat collecté uniquement pour la validation historique. Il reste hors fusion officielle." />)}</div></section>}

    <section className="rounded-2xl border border-slate-800 bg-[#0d131d] p-4"><div className="flex items-center gap-2"><Zap className="h-4 w-4 text-amber-300" /><h2 className="text-sm font-semibold text-slate-100">Régime opérationnel partagé</h2></div><div className="mt-3 flex items-start gap-3"><span className="text-3xl">{data.regimeEmoji}</span><div><p className="text-base font-bold text-slate-100">{data.regimeLabel}</p><p className="mt-0.5 text-xs text-slate-400">{data.regimeDescription}</p><p className="mt-1 text-[10px] text-blue-300">{data.regimeSourceLabel}{data.regimeSourceUpdatedAt ? ` · source à ${new Date(data.regimeSourceUpdatedAt).toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Paris" })}` : ""}</p></div></div><div className="mt-3 grid grid-cols-4 gap-1.5 text-center text-[10px]"><span className="rounded-lg bg-orange-400/10 py-1.5 text-orange-200">T° {Math.round(data.weights.temp * 100)}%</span><span className="rounded-lg bg-blue-400/10 py-1.5 text-blue-200">Pluie {Math.round(data.weights.precip * 100)}%</span><span className="rounded-lg bg-cyan-400/10 py-1.5 text-cyan-200">Vent {Math.round(data.weights.wind * 100)}%</span><span className="rounded-lg bg-slate-400/10 py-1.5 text-slate-200">Nuages {Math.round(data.weights.condition * 100)}%</span></div></section>

    <section className="rounded-2xl border border-slate-800 bg-[#0d131d] p-4"><div className="flex items-center gap-2"><BarChart3 className="h-4 w-4 text-blue-300" /><h2 className="text-sm font-semibold text-slate-100">Accord des modèles appliqués</h2></div>{hasTrace && data.modelDetails.length > 1 ? <><div className="mt-3 space-y-3"><Divergence label="Température" value={data.divergence.tempRange} max={10} unit="°C" color="bg-orange-400" /><Divergence label="Précipitations" value={data.divergence.precipRange} max={20} unit="mm" color="bg-blue-400" /><Divergence label="Vent" value={data.divergence.windRange} max={40} unit="km/h" color="bg-cyan-400" /></div><p className="mt-3 text-[11px] text-slate-500">Écart calculé entre les contributeurs de la trace actuelle.</p></> : <p className="mt-3 text-xs text-slate-500">Données insuffisantes : aucun écart inter-modèles n’est affiché sans plusieurs contributeurs tracés.</p>}</section>

    <section className="rounded-2xl border border-slate-800 bg-[#0d131d] p-4"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-violet-300" /><h2 className="text-sm font-semibold text-slate-100">Prévisions quotidiennes des contributeurs</h2></div>{data.modelDetails.length ? <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[380px] text-xs"><thead className="border-b border-slate-800 text-slate-500"><tr><th className="px-1 py-2 text-left font-medium">Modèle</th><th className="px-1 py-2 text-right font-medium">Poids</th><th className="px-1 py-2 text-right font-medium">Max</th><th className="px-1 py-2 text-right font-medium">Min</th><th className="px-1 py-2 text-right font-medium">Vent</th></tr></thead><tbody>{data.modelDetails.map((model) => <tr key={model.name} className="border-b border-slate-800/70 last:border-0"><td className="px-1 py-2 font-semibold text-slate-200">{model.label}</td><td className="px-1 py-2 text-right text-blue-300">{model.averageWeight == null ? "—" : `${Math.round(model.averageWeight * 100)}%`}</td><td className="px-1 py-2 text-right text-orange-200">{model.tempMax == null ? "—" : `${Number(model.tempMax).toFixed(1)}°`}</td><td className="px-1 py-2 text-right text-sky-200">{model.tempMin == null ? "—" : `${Number(model.tempMin).toFixed(1)}°`}</td><td className="px-1 py-2 text-right text-slate-300">{model.windSpeed == null ? "—" : `${Number(model.windSpeed).toFixed(1)}`}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-xs text-slate-500">Aucune prévision quotidienne persistée pour ce lieu.</p>}</section>

    <section className="rounded-2xl border border-slate-800 bg-[#0d131d] p-4"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-emerald-300" /><h2 className="text-sm font-semibold text-slate-100">Dernière collecte vérifiable</h2></div><Link href="/ranking" className="text-xs font-semibold text-blue-300">Fiabilité →</Link></div>{collection ? <><div className="mt-3 grid grid-cols-3 gap-2"><Stat label="Stations physiques" value={String(collection.physicalStationCount)} tone="text-emerald-300" /><Stat label="Modèles jour" value={String(collection.dailyModelCount)} tone="text-blue-300" /><Stat label="Modèles horaires" value={String(collection.hourlyModelCount)} tone="text-cyan-300" /></div><p className="mt-3 flex items-center gap-1 text-[11px] text-slate-400"><MapPin className="h-3 w-3" />Rayon {collection.radiusKm} km · état {collection.status} · {new Date(collection.collectedAt).toLocaleString("fr-FR", { dateStyle: "short", timeStyle: "short", timeZone: "Europe/Paris" })}</p></> : <p className="mt-3 text-xs text-slate-500">Aucun bilan de collecte n’est disponible pour ce lieu. Les stations ne sont pas présentées comme actives.</p>}</section>
  </main>;
}
