import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const pageSource = readFileSync(new URL("./WeatherDetails.tsx", import.meta.url), "utf8");
const timelineSource = readFileSync(new URL("../components/weather/ForecastByDaySection.tsx", import.meta.url), "utf8");
const styleSource = readFileSync(new URL("../index.css", import.meta.url), "utf8");
const selectedDetailsSource = readFileSync(new URL("../lib/hourlySelectedDetails.ts", import.meta.url), "utf8");
const displayDaysSource = readFileSync(new URL("../lib/forecastDayDisplay.ts", import.meta.url), "utf8");
describe("page Prévisions détaillées", () => {
  it("consomme les heures officielles étendues de la PR #103 et garde periodHours comme référence API séparée", () => {
    expect(pageSource).toContain("useOfficialForecast(activeLocation, { includeExtendedPeriods: true })");
    expect(pageSource).toContain("usePageWeatherSky({ includeExtendedPeriods: true })");
    expect(pageSource).toContain("dailyDays={data.days ?? []}");
    expect(pageSource).toContain("dailySources={data.modelsUsed ?? []}");
    expect(pageSource).toContain("hours={displayHours}");
    expect(pageSource).not.toContain("periodHours");
    expect(pageSource).not.toContain("includeExtendedPeriods: false");
    expect(displayDaysSource).toContain("kind: \"official-daily-fusion\"");
    expect(displayDaysSource).toContain("kind: \"official-hourly\"");
  });
  it("ancre la température de l'échéance active sur la mesure des stations physiques Netatmo", () => {
    expect(pageSource).toContain("useCurrentStationTemperature(coordinates)");
    expect(pageSource).toContain("withCurrentStationTemperature(hours, currentHourIdx, stationTemperature)");
    expect(pageSource).toContain("activeHourMeasurementLabel={stationTemperature?.provenanceLabel ?? null}");
    expect(timelineSource).toContain("activeHourMeasurementLabel");
    expect(timelineSource).toContain("Mesure stations physiques");
    expect(timelineSource).toContain(">Mesuré</span>");
    expect(timelineSource).toContain("température mesurée par les stations physiques");
  });
  it("limite les dates aux données réelles et protège la séparation officielle/référence", () => {
    expect(displayDaysSource).toContain("Math.min(15, Math.floor(maximumDays))");
    expect(displayDaysSource).toContain("groupOfficialHourlyForecastByDate(hours)");
    expect(displayDaysSource).toContain("if (current?.hourlyGroup) {");
    expect(displayDaysSource).toContain("if (includeDailyForHourlyDate.has(daily.date)) current.daily = daily");
    expect(displayDaysSource).toContain("isValidDateKey(daily.date)");
    expect(timelineSource).toContain('buildForecastDisplayDays(hours, dailyDays, 15, dailyDays.map(({ date }) => date ?? ""))');
    expect(timelineSource).toContain("{selectedDaily && <DailyForecastMetricsPanel");
    expect(timelineSource).toContain("Métriques quotidiennes indisponibles pour cette date.");
    expect(timelineSource).toContain("Fusion officielle · preuves par variable");
    expect(timelineSource).toContain("Sources quotidiennes réellement reçues");
    expect(timelineSource).toContain("Best Match · référence dérivée, non contributeur officiel");
    expect(timelineSource).toContain("aucun biais historique n’est appliqué aux valeurs futures");
    expect(timelineSource).toContain("l’heure exacte des runs modèles n’est pas fournie");
    expect(timelineSource).toContain("Best Match");
  });
  it("sépare disponibilité physique, calibration robuste et contributions sans score de confiance", () => {
    expect(timelineSource).toContain('diagnostic.availabilityStatus === "UNAVAILABLE"');
    expect(timelineSource).toContain('diagnostic.availabilityStatus === "SINGLE_MODEL"');
    expect(timelineSource).toContain("diagnostic.contributingModelCount === 1");
    expect(timelineSource).toContain('diagnostic.calibrationStatus === "PARTIALLY_CALIBRATED"');
    expect(timelineSource).toContain('diagnostic.calibrationStatus === "CALIBRATED"');
    expect(timelineSource).toContain("diagnosticsByVariable?.[key]");
    expect(timelineSource).toContain("Valeurs réellement disponibles :");
    expect(timelineSource).toContain("preuves historiques qualifiées :");
    expect(timelineSource).toContain("contributeurs effectifs");
    expect(timelineSource).toContain("ils ne constituent ni une note de fiabilité ni un pourcentage de confiance");
    expect(timelineSource).toContain("Une couverture plus faible peut être normale selon l’horizon du modèle.");
    expect(timelineSource).toContain("Nombre de modèles contributeurs :");
    expect(timelineSource).toContain("Incertitude statistique : non mesurée dans cette vue.");
    expect(timelineSource).toContain("Statut de calibration historique, distinct");
  });
  it("garde les rubans horizontaux accessibles et n’invente pas d’échéances pour la série quotidienne", () => {
    expect(timelineSource).toContain('aria-label="Jours de prévision défilables"');
    expect(timelineSource).toContain('aria-label="Heures de prévision défilables"');
    expect(timelineSource.match(/overflow-x-auto/g)?.length).toBeGreaterThanOrEqual(2);
    expect(timelineSource.match(/touch-pan-x/g)?.length).toBeGreaterThanOrEqual(2);
    expect(timelineSource.match(/snap-x snap-mandatory/g)?.length).toBeGreaterThanOrEqual(2);
    expect(timelineSource).toContain("centerWithinHorizontalStrip");
    expect(timelineSource).toContain("aria-pressed={isSelected}");
    expect(timelineSource).toContain("aria-pressed={isHourSelected}");
    expect(timelineSource).toContain("Aucune série horaire officielle n’est fournie pour cette date");
    expect(timelineSource).toContain("Métriques quotidiennes indisponibles pour cette date.");
  });
  it("place les jours puis les heures avant les détails de l’échéance sélectionnée", () => {
    const hourlyStrip = timelineSource.indexOf('aria-labelledby="forecast-hourly-strip-title"');
    const dailyStrip = timelineSource.indexOf('aria-labelledby="forecast-daily-strip-title"');
    const selectedValues = timelineSource.indexOf("Valeurs pour l’échéance sélectionnée");
    expect(hourlyStrip).toBeGreaterThanOrEqual(0);
    expect(dailyStrip).toBeGreaterThanOrEqual(0);
    expect(dailyStrip).toBeLessThan(hourlyStrip);
    expect(hourlyStrip).toBeLessThan(selectedValues);
    expect(timelineSource).not.toContain("Prévisions de l’échéance sélectionnée");
    expect(timelineSource).not.toContain("OfficialHourlyFieldCard");
  });
  it("agrandit les rubans, indique la pluie disponible et conserve les palettes thermiques", () => {
    expect(timelineSource).toContain("w-[5rem]");
    expect(timelineSource).toContain("<MeteoIcon name={icon} size={36} />");
    expect(timelineSource).toContain("w-fit min-w-[5.25rem]");
    expect(timelineSource).toContain("w-[7rem]");
    expect(timelineSource).toContain("<MeteoIcon name={weatherIconName} size={30}");
    expect(timelineSource).toContain('{day.date === today ? "Aujourd’hui" : shortWeekday(day.date)}');
    expect(timelineSource).toContain(">Max</span>");
    expect(timelineSource).toContain(">Min</span>");
    expect(timelineSource).not.toContain('day.daily.officialFusion ? "Fusion" : "Quotidien"');
    expect(timelineSource).not.toContain("Extrêmes quotidiens ·");
    expect(timelineSource).toContain("whitespace-nowrap text-2xl font-bold leading-none tabular-nums text-white sm:text-3xl");
    expect(timelineSource).toContain("entry.hour.precipitation > 0");
    expect(timelineSource).toContain("getTemperatureTone(entry.hour.temp, \"hourly\")");
    expect(timelineSource).toContain('getExtremeTemperatureTone("max", day.daily?.tempMax)');
    expect(timelineSource).toContain('getExtremeTemperatureTone("min", day.daily?.tempMin)');
  });
  it("affiche les composantes horaires fournies et garde hors panneau les catégories exclues", () => {
    for (const title of ["Précipitations", "Averses", "Neige", "Vent", "Humidité et rosée", "Nuages", "Pression", "Indice UV", "Température ressentie", "Visibilité"]) {
      expect(selectedDetailsSource).toContain(`"${title}"`);
    }
    expect(selectedDetailsSource).not.toContain('"Pluie"');
    expect(selectedDetailsSource).toContain("rafales");
    expect(selectedDetailsSource).toContain("direction");
    expect(selectedDetailsSource).not.toContain("Type et intensité");
    expect(selectedDetailsSource).not.toContain("Rayonnement solaire");
    expect(selectedDetailsSource).not.toContain("Code météo (WMO)");
    expect(selectedDetailsSource).not.toContain('"precip-type"');
    expect(selectedDetailsSource).not.toContain('"weather-code"');
    expect(selectedDetailsSource).toContain("formatHourlyPrecipitationComponentValues");
    expect(selectedDetailsSource).toContain("hasPositiveSnowfall");
    expect(selectedDetailsSource).toContain("isSnowWmoWeatherCode(hour.weatherCode)");
    expect(selectedDetailsSource).toContain("Non disponible");
    expect(selectedDetailsSource).toContain("Aucune donnée horaire de qualité de l’air");
    expect(timelineSource).toContain("Soleil");
    expect(selectedDetailsSource).toContain("fréquence descriptive brute, pas une probabilité calibrée");
    expect(timelineSource).toContain("jamais une probabilité de pluie calibrée");
    expect(timelineSource).toContain("buildDailyDetailCategories");
    expect(timelineSource).toContain("L’indice de qualité de l’air ne fait pas partie des données renvoyées à cette page");
    expect(timelineSource).toContain("Aucune valeur n’est demandée, déduite ou inventée");
  });
  it("garde les valeurs sur l’heure cliquée, supprime les métadonnées sous le titre et conserve la provenance ailleurs", () => {
    expect(timelineSource).toContain("buildHourlyDetailCategories(selectedEntry, hours, indexedHours, histogramStartValidAt)");
    expect(timelineSource).toContain("getHourlyHistogramStartValidAt(");
    expect(timelineSource).toContain("buildHourlyHistogramSeries(detail.key, indexedHours, startValidAt)");
    expect(timelineSource).toContain("<HourlyMiniHistogram");
    expect(timelineSource).toContain("allHours={hours}");
    expect(timelineSource).toContain("selectedEntry?.hour.validAt");
    expect(timelineSource).toContain("validTime UTC :");
    expect(timelineSource).not.toContain("Source : {selectedSourceLabel}");
    expect(timelineSource).not.toContain("<OfficialForecastCalculationTimes");
    expect(timelineSource).toContain('aria-label="Prévision, source et fraîcheur"');
    expect(timelineSource).toContain('hourlyFieldProvenance("temperature"');
    expect(timelineSource).not.toContain("Valeur de l’échéance sélectionnée · {category.rows[0]?.time");
    expect(timelineSource).toContain("fallback?.provider");
    expect(timelineSource).toContain("réponse reçue ${freshness} · fraîcheur amont inconnue");
    expect(timelineSource).toContain("fraîcheur amont inconnue");
    expect(timelineSource).toContain("whitespace-normal break-words");
    expect(pageSource).toContain("officialProvenance={{");
    expect(pageSource).toContain("source: data.officialSnapshot?.source");
    expect(pageSource).toContain("hourlyComputedAt: data.officialSnapshot?.hourlyComputedAt");
    expect(pageSource).toContain("computedAt: data.officialSnapshot?.computedAt");
  });
  it("préserve la navigation historique, la carte et les preuves horaires", () => {
    expect(pageSource).toContain('import { Link } from "wouter"');
    expect(pageSource).toContain("Historique des prévisions");
    expect(pageSource).toContain('href="/history"');
    expect(pageSource).toContain("<WindyMap");
    expect(pageSource).toContain("<HourlyHistoricalEvidencePanel");
    expect(pageSource).toContain("getActiveOfficialForecastHour(data.hours, Date.now())");
    expect(pageSource).toContain("Prévisions temporairement indisponibles");
    expect(pageSource).toContain("forecast-details-page");
    expect(pageSource).toContain("pb-24");
  });
  it("sépare la vérification admin du catalogue de la comparaison de valeurs AROME/Single Runs", () => {
    expect(pageSource).toContain("trpc.weather.verifyHondeghemAromeWindDirection.useMutation()");
    expect(pageSource).toContain('onClick={() => windDirectionVerification.mutate()}');
    expect(pageSource).toContain("ne télécharge ni raster AROME ni valeurs Single Runs");
    expect(pageSource).toContain("elle ne télécharge ni raster AROME ni valeurs Single Runs et n’intègre pas automatiquement le champ");
    expect(pageSource).toContain('{user?.role === "admin" && <MeteoSurface');
  });
  it("garde OpenWeather comme comparateur manuel shadow et affiche les échéances et champs non couverts", () => {
    expect(pageSource).toContain("trpc.weather.compareOpenWeatherShadow.useMutation()");
    expect(pageSource).toContain("validAt,");
    expect(pageSource).toContain("openWeatherShadow.data.provenance.endpoint");
    expect(pageSource).toContain("openWeatherShadow.data.coverage.map");
    expect(pageSource).toContain("openWeatherShadow.data.unsupportedFields.map");
    expect(pageSource).toContain("aucun changement des prévisions officielles");
    expect(pageSource).toContain("jamais un modèle ni un vote");
  });
  it("rend visibles la fraîcheur, l’origine, la sélection et les états accessibles", () => {
    expect(timelineSource).toContain('aria-label="Prévision, source et fraîcheur"');
    expect(timelineSource).toContain("selectedValidAt={category.validAt}");
    expect(timelineSource).toContain("getCategoryPalette(category.key)");
    expect(pageSource).toContain('aria-label="Chargement des prévisions"');
    expect(timelineSource).toContain("Aucune prévision disponible");
    expect(styleSource).toContain("forecast-selected-summary-enter 180ms");
    expect(styleSource).toContain("@media (prefers-reduced-motion: reduce)");
  });
});
