import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

describe("Weather AI Lab — transparence de fusion", () => {
  it("centralise la méthode et les sources de fusion hors du Dashboard", () => {
    const source = readFileSync(new URL("./WeatherAILab.tsx", import.meta.url), "utf8");
    expect(source).toContain("Simulation de la fusion");
    expect(source).toContain("Pondération finale");
    expect(source).toContain("Poids réellement appliqués par paramètre");
    expect(source).toContain('key: "humidity"');
    expect(source).toContain("Aucune trace disponible.");
    expect(source).toContain("Résultat officiel");
    expect(source).toContain("Données exploitables");
    expect(source).toContain("Régime de prévision dominant");
    expect(source).toContain("Le Dashboard indique séparément le phénomène immédiat");
    expect(source).toContain("Lexique, méthode et sources");
    expect(source).toContain("AI_LAB_GLOSSARY");
    expect(source).toContain("MeteoAI en quelques mots");
    expect(source).toContain("Comparer avant de privilégier");
    expect(source).toContain("Apprendre sans réécrire le passé");
    expect(source).toContain("Expliquer les limites");
    expect(source).toContain("Confiance");
    expect(source).toContain("Stabilité des modèles");
    expect(source).toContain("Données insuffisantes / —");
    expect(source).toContain("group-open:rotate-180");
    expect(source).toContain("Horizon de prévision");
    expect(source).toContain("MAE");
    expect(source).toContain("RMSE");
    expect(source).toContain("Seuils de décision");
    expect(source).toContain("Observations réelles et analyse nocturne");
    expect(source).toContain("Prévisions de référence · 05 h 00");
    expect(source).toContain("Analyse de nuit · 00 h 30");
    expect(source).toContain("Journée qualifiée");
    expect(source).toContain("Comparaison et scores");
    expect(source).toContain("ce n’est donc pas un score immédiat affiché au soir");
    expect(source).toContain("Correction de biais");
    expect(source).toContain("Maille et microclimat");
    expect(source).toContain("Sources, provenance et cartes");
    expect(source).toContain("Netatmo Weather API");
    expect(source).toContain("Google Maps JavaScript API");
    expect(source).toContain("Astronomy Engine");
    expect(source).toContain("Visibilité d’éclipse");
    expect(source).toContain("Ces modèles sont archivés pour une validation historique");
    expect(source).toContain("gain de fiabilité n’est pas mesuré");
    expect(source).toContain("Calcul de l’indicateur");
    expect(source).toContain("40 % accord des modèles");
    expect(source).toContain("60 % de stabilité des températures maximales");
    expect(source).toContain("poids final strictement positif");
    expect(source).toContain("PopoverClose");
    expect(source).toContain("h-6 w-6");
    expect(source).toContain("Simulation de la fusion");
    expect(source).toContain("Snapshot retenu");
    expect(source).toContain("Collecte des modèles");
    expect(source).toContain("Pondération finale");
    expect(source).toContain("Résultat officiel");
    expect(source).toContain("Résultat final · contexte des stations locales");
    expect(source).toContain("Aucune station physique locale active");
    expect(source).toContain("grid-cols-[minmax(90px,0.72fr)_minmax(0,1.5fr)]");
    expect(source).toContain("before:bg-sky-300/20");
    expect(source).toContain("Étape {activeStep + 1} sur {steps.length}");
    expect(source).toContain("Branche complémentaire · Stations locales");
    expect(source).toContain("Recherche locale");
    expect(source).toContain("Filtre physique");
    expect(source).toContain("Synthèse locale");
    expect(source).toContain("Preuve qualifiée");
    expect(source).toContain("getEvidenceStatus");
    expect(source).toContain("getForecastCollectionReport");
    expect(source).toContain("Collecte de prévisions");
    expect(source).toContain("Relevé de {forecastCollectionReport?.scheduledAt");
    expect(source).toContain("Les stations physiques relèvent d’un flux d’observations séparé.");
    expect(source).toContain("dailyCollectedModels.map");
    expect(source).toContain('import { BackToTopButton } from "@/components/BackToTopButton"');
    expect(source).toContain("<BackToTopButton />");
    expect(source).toContain('className="order-[-1] grid grid-cols-3 gap-2"');
    expect(source).toContain('className="order-[-2] flex items-center justify-between gap-2"');
  });

  it("présente explicitement la dernière fusion archivée sans la confondre avec la prévision actuelle", () => {
    const source = readFileSync(new URL("./WeatherAILab.tsx", import.meta.url), "utf8");
    expect(source).toContain("snapshotStatus");
    expect(source).not.toContain("Dernière fusion archivée");
    expect(source).toContain("photo enregistrée à un moment précis");
    expect(source).toContain("photo conservée des modèles reçus");
    expect(source).not.toContain("Débuter dans l’AI Lab");
    expect(source).not.toContain("Lire l’écran en trois gestes");
    expect(source).not.toContain("SnapshotPhotoGuide");
    expect(source).not.toContain(">Actualiser</button>");
    expect(source).toContain('"Relancer"');
  });

  it("propose une relance manuelle pour le lieu favori avec ses états explicites", () => {
    const source = readFileSync(new URL("./WeatherAILab.tsx", import.meta.url), "utf8");
    expect(source).toContain("refreshManualFusion");
    expect(source).toContain("Relancer");
    expect(source).toContain("Fusion relancée avec");
    expect(source).toContain("Une fusion vient déjà d’être calculée");
  });
});
