import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const source = readFileSync(new URL("./EnvironmentalPanels.tsx", import.meta.url), "utf8");
const lunarGlobeSource = readFileSync(new URL("./LunarPhaseGlobe.tsx", import.meta.url), "utf8");
const lunarWebglSource = readFileSync(new URL("../lib/lunarWebgl.ts", import.meta.url), "utf8");
const solarGlobeSource = readFileSync(new URL("./SolarGlobe.tsx", import.meta.url), "utf8");
const solarWebglSource = readFileSync(new URL("../lib/solarWebgl.ts", import.meta.url), "utf8");
const styles = readFileSync(new URL("../index.css", import.meta.url), "utf8");
const celestialSvgPathsSource = readFileSync(new URL("../lib/celestialSvgPaths.ts", import.meta.url), "utf8");
const apparentSunMoonSource = source.slice(source.indexOf("function SunMoonPanelApparent"), source.indexOf("export function EnvironmentalPanels"));
const trajectorySunMoonSource = source.slice(source.indexOf("function SunMoonPanelTrajectory"), source.indexOf("export function EnvironmentalPanels"));
const temporalSunMoonSource = source.slice(source.indexOf("function SunMoonPanelTemporal"), source.indexOf("export function EnvironmentalPanels"));

describe("EnvironmentalPanels", () => {
  it("offre un recentrage accessible à côté des contrôles de zoom des cartes OSM", () => {
    expect(source).toContain("MapRecenterButton");
    expect(source).toContain("Recentrer la carte sur le lieu actif");
    expect(source).toContain("map.setView([center.lat, center.lon], isExpanded ? ECLIPSE_IMMERSIVE_WORLD_ZOOM : 5)");
    expect(source).toContain("map.setBearing(0)");
    expect(source).toContain("enableRotation={isExpanded}");
  });

  it("présente la qualité de l’air avec ses mesures réelles et son attribution", () => {
    expect(source).toContain("Qualité de l’air");
    expect(source).toContain("PM2.5");
    expect(source).toContain("Prévision de qualité de l’air");
    expect(source).toContain("Prochaines 24 h");
  });

  it("présente les éphémérides Soleil et Lune sans substituer de données", () => {
    expect(source).toContain("Soleil & Lune");
    expect(source).toContain("Éphémérides locales du jour");
    expect(source).toContain("Éclairage");
    expect(apparentSunMoonSource).toContain("Hauteur apparente");
    expect(apparentSunMoonSource).toContain("Mise à jour automatique toutes les minutes avec Astronomy Engine");
    expect(apparentSunMoonSource).toContain("La Lune reste fixe à sa coordonnée calculée");
    expect(apparentSunMoonSource).toContain("Lecture et limites");
    expect(source).toContain("Éphémérides réelles temporairement indisponibles");
    expect(source).toContain("Prochains repères astronomiques");
    expect(source).toContain("Prochaine pleine lune");
    expect(source).toContain("Autres phases");
    expect(source).toContain("Alerte astronomique");
    expect(source).toContain("Visibilité à confirmer selon l’horizon local");
    expect(source).toContain("distinct des alertes météo");
    expect(source).toContain("Étoiles filantes");
    expect(source).toContain("météores/h au zénith dans des conditions idéales");
    expect(source).toContain("Carte locale d’observation");
    expect(source).toContain("Il ne représente pas la bande géométrique d’une éclipse");
    expect(source).toContain("function getMapTitle");
    expect(source).toContain("Zones de visibilité d’éclipse");
    expect(source).toContain("Zones de nuit des étoiles filantes");
    expect(source).toContain("const eventMapLayers = outlook.eventMapLayers");
    expect(source).toContain("setSelectedLayerId(firstLayerId)");
    expect(source).toContain("AstronomyEventSelector");
    expect(source).toContain("setSelectedPoint(null)");
    expect(source).toContain("Nuit astronomique");
    expect(source).toContain("Bande centrale NASA");
    expect(source).toContain("eclipseMapLayers");
    expect(source).toContain("Agrandir la carte");
    expect(source).toContain("function getExpandedMapTitle");
    expect(source).toContain("Carte de visibilité d’éclipse");
    expect(source).toContain("const onMapReady = (map: L.Map, isExpanded: boolean)");
    expect(source).toContain("L.rectangle([[cell.north, cell.west], [cell.south, cell.east]]");
    expect(source).toContain('color: isFull ? "#0284c7" : "#7c3aed"');
    expect(source).toContain("fillOpacity: baseOpacity * (visibilityOpacity / 100)");
    expect(source).toContain('rectangle.on("click", (event: L.LeafletMouseEvent)');
    expect(source).toContain('polygon.on("click", (event: L.LeafletMouseEvent)');
    expect(source).toContain("rectangle.setStyle({ fillOpacity: baseOpacity * scale })");
    expect(source).toContain("L.polyline(selectedLayer.centralPath.centerLine");
    expect(source).toContain("visibilityOpacity");
    expect(source).toContain("Opacité des zones de visibilité");
    expect(source).toContain("Opacité <span>{visibilityOpacity}%</span>");
    expect(source).toContain('type="range" min="0" max="100" step="1"');
    expect(source).toContain("onPointerMove={(event) => {");
    expect(source).toContain("setPointerCapture(event.pointerId)");
    expect(source).toContain("releasePointerCapture(event.pointerId)");
    expect(styles).toContain("touch-action: none");
    expect(source).toContain("{isExpanded && opacityControl}");
    expect(source).toContain("SlidersHorizontal");
    expect(source).toContain("isOpacityPanelOpen");
    expect(source).toContain("absolute bottom-16 left-3");
    expect(source).toContain("Régler l’opacité des zones de visibilité");
    expect(source).toContain("openExpandedMap");
    expect(source).toContain("Le plein écran du navigateur n’est pas disponible");
    expect(source).toContain("document.documentElement.requestFullscreen()");
    expect(source).toContain("isMapOpeningRef");
    expect(source).toContain("map.invalidateSize({ animate: false, pan: false })");
    expect(styles).toContain("map-opacity-control");
    expect(source).toContain("interactive={isExpanded}");
    expect(source).toContain("enableRotation={isExpanded}");
    expect(source).toContain('map.on("rotate", updateExpandedHeading)');
    expect(source).toContain("setExpandedHeading(map.getBearing())");
    expect(source).toContain("map.setBearing(0)");
    expect(source).toContain("allowPageScroll={!isExpanded}");
    expect(source).toContain("map.setView(localPosition, 5)");
    expect(source).toContain("Le cadrage de toutes les cellules peut tomber trop loin sur mobile");
    expect(source).toContain("ECLIPSE_IMMERSIVE_WORLD_ZOOM = 2.35");
    expect(source).toContain("map.setView(localPosition, ECLIPSE_IMMERSIVE_WORLD_ZOOM)");
    expect(source).toContain('localMarkerContent.className = "eclipse-user-location-marker"');
    expect(source).toContain('mapContent("compact", "h-[280px]")');
    expect(source).toContain("Me localiser");
    expect(source).toContain("getEclipseCircumstances");
    expect(source).toContain("Cliquez sur une zone de visibilité");
    expect(source).toContain("Azimut :");
    expect(source).toContain("nord géographique");
    expect(source).toContain("Localisation en cours");
    expect(source).toContain("eclipse-user-location-marker");
    expect(source).toContain("Centrer la carte sur ma position");
    expect(source).toContain('absolute right-3 top-3 z-20');
    expect(source).toContain("MapControlButton");
    expect(source).toContain("MapZoomControl");
    expect(styles).toContain("Carte d’éclipse immersive");
    expect(styles).toContain('[data-slot="dialog-content"]:has([aria-label="Fermer la carte agrandie"])');
    expect(styles).toContain("position: fixed !important");
    expect(styles).toContain("translate: 0 0 !important");
    expect(styles).toContain('class*="max-h-\\[calc\\(100dvh-1\\.25rem\\)\\]"');
    expect(styles).toContain("min-width: 100vw !important");
    expect(styles).toContain("translate: none !important");
    expect(source).toContain('className={isExpanded ? "eclipse-map-viewport" : height}');
    expect(styles).toContain(".eclipse-map-viewport");
    expect(styles).toContain("z-index: 60 !important");
    expect(styles).toContain("pointer-events: auto !important");
    expect(styles).toContain("Radix désactive les pressions hors de son dialogue");
    expect(styles).toContain("height: 100dvh !important");
    expect(styles).toContain("display: none");
    expect(source).toContain('absolute right-3 top-[calc(28%+2.5rem)] z-20 flex flex-col items-center gap-4');
    expect(source).toContain("MapZoomControl onZoomIn={() => adjustExpandedZoom(1)}");
    expect(source).toContain("adjustExpandedZoom");
    expect(source).toContain("Math.abs(expandedHeading) > 0.5");
    expect(source).toContain("Réorienter la carte vers le nord");
    expect(source).toContain("onClick={resetExpandedMapBearing}");
    expect(source).toContain("interactive={isExpanded}");
    expect(source).toContain('absolute bottom-12 right-3 z-20');
    expect(source).toContain("MapZoomControl onZoomIn={() => { const map = compactMapRef.current;");
    expect(source).toContain("const compassHeading = deviceHeading == null ? expandedHeading");
    expect(source).toContain("deviceHeading");
    expect(source).toContain("orientationStatus");
    expect(source).toContain("DeviceOrientationEvent");
    expect(source).toContain("webkitCompassHeading");
    expect(source).toContain("requestPermission");
    expect(source).toContain("deviceorientationabsolute");
    expect(source).toContain("window.screen.orientation?.angle");
    expect(source).toContain("headingSource");
    expect(source).toContain("headingSourceRef");
    expect(source).toContain('if (!hasAbsoluteHeading && headingSourceRef.current === "absolute") return;');
    expect(source).toContain("Cap relatif détecté");
    expect(source).toContain("Activez l’orientation absolue");
    expect(source).toContain("relativeHeadingOffset");
    expect(source).toContain("Calibrer le nord");
    expect(source).toContain("Calibrer sur le nord");
    expect(source).toContain("Boussole relative calibrée sur le nord");
    expect(source).toContain("Bougez le téléphone");
    expect(source).toContain("map-compass-status");
    expect(source).toContain('map-compass-status absolute left-3 top-[208px] z-20 w-[188px]');
    expect(styles).toContain("top: 8.5rem !important");
    expect(styles).toContain(".eclipse-map-viewport .map-compass-status");
    expect(styles).toContain("top: 11rem !important");
    expect(source).toContain("Autorisez Mouvement et orientation dans les réglages du navigateur.");
    expect(styles).toContain("La colonne compacte porte elle-même l’aide");
    expect(styles).toContain(".map-compass-status button");
    expect(source).toContain("Capteur refusé");
    expect(source).toContain("Capteur indisponible");
    expect(source).toContain("Cap ${Math.round(compassHeading)}°");
    expect(source).toContain("Activer la boussole du téléphone");
    expect(source).not.toContain("Désactiver la boussole du téléphone");
    expect(source).toContain("Touchez la rose des vents");
    expect(source).toContain("orientationStatus !== \"waiting\"");
    expect(source).not.toContain("bottom-[112px] right-3");
    expect(source).not.toContain("MapTypeToggle");
    expect(source).not.toContain("setMapTypeId");
    expect(source).not.toContain("google.maps");
    expect(source).not.toContain("streetViewControl");
    expect(source).not.toContain("flex flex-col items-end gap-3");
    expect(source).toContain("isMapExpanded ? expandedMapRef.current : compactMapRef.current");
    expect(source).toContain("setView([point.lat, point.lng], Math.max(activeMap.getZoom() ?? 4, 9))");
    expect(source).toContain("Maximize2");
    expect(source).toContain("LocateFixed");
    expect(source).not.toContain("streetViewControl");
    expect(source).not.toContain('gestureHandling: "greedy"');
    expect(source).toContain("utilisez les contrôles de zoom et la flèche de direction");
    expect(source).toContain("Activer la boussole du téléphone depuis la rose des vents");
    expect(source).toContain("COMPASS_ROSE_POINTS");
    expect(source).not.toContain('label: "NNE"');
    expect(source).not.toContain('label: "ENE"');
    expect(source).toContain('label: "NE"');
    expect(source).toContain('label: "SO"');
    expect(source).not.toContain('label: "OSO"');
    expect(source).not.toContain('label: "NNO"');
    expect(source).toContain("Touchez la rose des vents");
    expect(source).toContain("nearestCompassRosePoint");
    expect(source).toContain("bg-amber-300");
    expect(source).toContain("astronomicalBodyLabel");
    expect(source).toContain("eclipse-compass-shell");
    expect(source).toContain("eclipse-compass-cardinal-arrow");
    expect(source).toContain("eclipse-compass-label--cardinal");
    expect(source).toContain("eclipse-compass-label--intercardinal");
    expect(source).toContain("h-[124px] w-[124px]");
    expect(source).toContain("displayedArrowRotation");
    expect(source).toContain("shortestRotation");
    expect(source).toContain("eclipse-compass-center-pulse");
    expect(source).toContain("MOON_ALIGNMENT_TOLERANCE_DEG");
    expect(source).toContain("getAngularDistance");
    expect(source).toContain("hasReliableCompassHeading");
    expect(source).toContain("isMoonAligned");
    expect(source).toContain("moonAlignmentProximity");
    expect(source).toContain("isMoonGuidanceActive");
    expect(source).toContain("navigator.vibrate(18)");
    expect(source).toContain("moonAlignmentHapticRef");
    expect(source).not.toContain("toggleLunarObservationFullscreen");
    expect(source).toContain("requestFullscreen");
    expect(source).toContain("moonObservationQuery");
    expect(source).toContain("Distance Terre–Lune");
    expect(source).toContain("formatLunarDistance");
    expect(source).toContain("eclipse-moon-alignment-ring");
    expect(source).toContain("Lune alignée");
    expect(source).toContain('eclipse-moon-alignment-label absolute left-1/2 top-1/2');
    expect(source).toContain("eclipse-astro-guidance-arrow");
    expect(source).toContain("eclipse-astro-guidance-arrow__beam");
    expect(source).toContain("eclipse-astro-guidance-arrow__head");
    expect(source).toContain("#38bdf8");
    expect(source).toContain("eclipse-astro-bearing");
    expect(styles).toContain("Instrument de guidage astronomique");
    expect(styles).toContain(".eclipse-compass-ring");
    expect(styles).toContain(".eclipse-compass-cardinal-arrow");
    expect(styles).toContain(".eclipse-compass-label--cardinal");
    expect(styles).toContain(".eclipse-compass-center-pulse");
    expect(styles).toContain(".eclipse-compass-shell.eclipse-moon-aligned");
    expect(styles).toContain(".eclipse-moon-alignment-ring");
    expect(styles).toContain(".eclipse-moon-alignment-label");
    expect(styles).toContain("top: 50%");
    expect(styles).toContain("transform: translate(-50%, -50%)");
    expect(styles).toContain("rgb(168 85 247 / 0.34)");
    expect(styles).toContain("rgb(6 182 212 / 0.26)");
    expect(styles).toContain("--moon-guidance-opacity");
    expect(styles).toContain("--moon-guidance-scale");
    expect(styles).toContain("transition: transform 420ms");
    expect(styles).toContain("@keyframes eclipse-compass-center-pulse");
    expect(styles).toContain(".eclipse-astro-guidance-arrow");
    expect(styles).toContain(".eclipse-astro-guidance-arrow__head");
    expect(styles).toContain(".eclipse-compass-shell::after");
    expect(styles).toContain("conic-gradient(from -11.25deg");
    expect(styles).toContain("rgb(34 211 238 / 0.78)");
    expect(styles).toContain("rgb(1 8 22 / 0.96) 36% 43%");
    expect(styles).toContain(".eclipse-compass-cardinal-arrow");
    expect(styles).toContain("stroke-width: 1.2");
    expect(styles).toContain("transform: scaleX(0.56) scaleY(1.08)");
    expect(styles).toContain(".eclipse-astro-bearing");
    expect(styles).toContain(".lunar-live-panel");
    expect(styles).toContain(".lunar-live-panel__metric");
    expect(source).toContain("Repère de rose");
    expect(source).toContain("Détails de la boussole");
    expect(source).toContain("Boussole du téléphone active. Cap");
    expect(source).toContain("map-control-cluster absolute left-3 top-3 z-20");
    expect(source).toContain("isCompassDetailsOpen");
    expect(source).toContain("Comment lire la boussole");
    expect(source).not.toContain("Recentrer sur la zone initiale de l’éclipse");
    expect(source).not.toContain("RotateCcw");
    expect(source).toContain("astronomicalAzimuthLabel");
    expect(source).toContain("Azimut de l’astre");
    expect(source).toContain("astronomicalDirection");
    expect(source).toContain("isAstroObservableNow");
    expect(source).toContain("fenêtre calculée d’observabilité");
    expect(source).toContain("Calcul astronomique : vérifiez l’horizon, les nuages");
    expect(source).toContain("Ma position actuelle");
    expect(source).toContain("soundAlertEnabled");
    expect(source).not.toContain("Activer l’alerte sonore");
    expect(source).not.toContain("Alerte sonore d’observabilité");
    expect(source).not.toContain("un son discret est joué une seule fois");
    expect(source).not.toContain("setIsSoundHelpOpen(true)");
    expect(source).toContain('role="status"');
    expect(source).not.toContain("Alerte sonore.");
    expect(source).not.toContain("RotateCcw");
    expect(source).toContain("observationAlertFiredRef");
    expect(source).toContain("map-control-cluster");
    expect(styles).toContain("Groupes de commandes flottantes");
    expect(source).toContain("data-swipe-exclude");
    expect(source).toContain("🌕 Prochaine pleine lune");
    expect(source).toContain("Icône d’éclipse");
    expect(source).toContain("Icône de pluie de météores");
    expect(source).toContain("Icône de pleine lune");
    expect(source).toContain("astronomy-outlook-panel");
    expect(styles).toContain("Alertes astronomiques : les informations secondaires restent lisibles");
  });

  it("ouvre des modales de détail accessibles depuis les deux panneaux", () => {
    expect(source).toContain("DialogTrigger");
    expect(source).toContain("Voir les détails");
    expect(source).toContain("Détails de l’indice et des polluants");
    expect(source).toContain("À propos</span>{description}");
    expect(source).toContain("uppercase tracking-[0.12em] text-sky-200/75");
    expect(source).toContain('aria-label="Fermer l’aide"');
    expect(apparentSunMoonSource).toContain("Positions apparentes réelles et actualisées localement pour le lieu actif.");
  });

  it("préserve l’arche complète du cycle solaire sur mobile", () => {
    expect(source).toContain("rounded-t-full");
    expect(temporalSunMoonSource).toContain("w-full max-w-[330px] min-w-0 overflow-visible");
    expect(temporalSunMoonSource).toContain('belowHorizon && <p className="celestial-below-horizon-label min-w-0">');
    expect(styles).toContain(".celestial-below-horizon-label {");
    expect(styles).not.toContain('section[aria-label="Qualité de l’air, soleil et lune"] > :nth-child(2)');
    expect(styles).not.toContain("bottom: -2.1rem !important");
    expect(styles).toContain("celestial-solar-disc-breathe");
    expect(styles).toContain("prefers-reduced-motion: no-preference");
  });

  it("distingue les positions du Soleil et de la Lune à partir de coordonnées apparentes réelles", () => {
    expect(apparentSunMoonSource).toContain("getApparentAstronomyPosition.useQuery");
    expect(apparentSunMoonSource).toContain("refetchInterval: 60_000");
    expect(apparentSunMoonSource).toContain("projectApparentBodyOnArc");
    expect(celestialSvgPathsSource).toContain("left: 50 - 42 * Math.sin(azimuthRadians)");
    expect(celestialSvgPathsSource).toContain("Math.sin(altitudeRadians)");
    expect(apparentSunMoonSource).toContain("sunArc");
    expect(apparentSunMoonSource).toContain("moonArc");
    expect(apparentSunMoonSource).toContain("formatAzimuth(apparentPosition.sun.azimuthDeg)");
    expect(apparentSunMoonSource).toContain("formatAzimuth(apparentPosition.moon.azimuthDeg)");
    expect(apparentSunMoonSource).toContain('MeteoIcon name="clear_night" size={40}');
    expect(apparentSunMoonSource).toContain("celestial-night-marker");
    expect(apparentSunMoonSource).toContain('relative mx-auto mt-7 h-40');
    expect(apparentSunMoonSource).toContain("Position apparente de la Lune");
    expect(apparentSunMoonSource).not.toContain("celestial-moon-axis-rotation");
    expect(styles).not.toContain("@keyframes celestial-moon-axis-rotation");
    expect(styles).not.toContain("rotateY(360deg)");
    expect(apparentSunMoonSource).toContain("h-12 w-12");
    expect(styles).not.toContain('content: "Nuit locale"');
  });

  it("trace les parcours réels du Soleil et de la Lune sur un ciel crépusculaire sans rotation lunaire", () => {
    expect(source).toContain("buildTrajectoryPath");
    expect(trajectorySunMoonSource).toContain("position.trajectory?.sun");
    expect(trajectorySunMoonSource).toContain("position.trajectory?.moon");
    expect(trajectorySunMoonSource).toContain("celestial-trajectory--sun");
    expect(trajectorySunMoonSource).toContain("celestial-trajectory--moon");
    expect(trajectorySunMoonSource).toContain("celestial-arc-backdrop");
    expect(trajectorySunMoonSource).toContain("Lune réaliste fixe");
    expect(trajectorySunMoonSource).toContain("sans rotation");
    expect(styles).toContain("celestial-trajectory-card");
    expect(styles).toContain("celestial-trajectory--sun");
    expect(styles).toContain("celestial-trajectory--moon");
    expect(styles).toContain("stroke-dasharray");
  });

  it("place des repères horaires visibles et adapte le ciel à la hauteur réelle du Soleil", () => {
    expect(source).toContain("selectTrajectoryTimeMarkers");
    expect(source).toContain("getCelestialLightPhase");
    expect(temporalSunMoonSource).toContain("sunTimeMarkers");
    expect(temporalSunMoonSource).toContain("moonTimeMarkers");
    expect(temporalSunMoonSource).toContain('celestial-time-marker--sun');
    expect(temporalSunMoonSource).toContain('celestial-time-marker--moon');
    expect(temporalSunMoonSource).toContain('celestial-trajectory-card--${lightPhase}');
    expect(temporalSunMoonSource).toContain('celestial-arc-scene--${lightPhase}');
    expect(styles).toContain("celestial-trajectory-card--day");
    expect(styles).toContain("celestial-trajectory-card--twilight");
    expect(styles).toContain("celestial-trajectory-card--night");
    expect(styles).toContain("celestial-time-markers");
  });

  it("affiche la phase, l’éclairage et l’orientation issus du calcul géométrique lunaire", () => {
    expect(temporalSunMoonSource).toContain("position.lunar");
    expect(source).toContain("brightLimbAngleDeg");
    expect(source).toContain("illuminationPct");
    expect(temporalSunMoonSource).toContain("displayTimeInZone(value, astronomy.timezone)");
    expect(source).toContain("Visibilité locale");
    expect(source).toContain("getEclipseCircumstances.useQuery");
    expect(source).toContain("isEclipseInProgress");
    expect(source).toContain("eclipse-visibility-live");
    expect(source).toContain("Suivi plein écran");
    expect(source).toContain("Quitter le plein écran");
    expect(source).toContain("Alerte visuelle");
    expect(source).toContain("Alerte sonore");
    expect(source).toContain("L’éclipse commence maintenant");
    expect(temporalSunMoonSource).toContain("<RealisticMoon phase={moonPhase}");
    expect(temporalSunMoonSource).toContain("const moonPhase = position.lunar ?? astronomy.lunar");
    expect(temporalSunMoonSource).toContain("moonPhase.label");
    expect(temporalSunMoonSource).toContain("moonPhase.illuminationPct");
  });

  it("utilise une sphère WebGL texturée pour la Lune et un fallback 2D explicite", () => {
    expect(source).toContain("function RealisticMoon");
    expect(source).toContain("<LunarPhaseGlobe phase={phase} size={size} alt={alt} />");
    expect(source).toContain("NASA's Scientific Visualization Studio");
    expect(source).not.toContain("overflow-hidden rounded-full bg-slate-950");
    expect(source).not.toContain("ring-1 ring-slate-200/20");
    expect(source).not.toContain("realistic-moon-glow");
    expect(lunarWebglSource).toContain("gl.drawArrays(gl.TRIANGLES");
    expect(lunarWebglSource).toContain("getLunarSunDirection");
    expect(lunarWebglSource).toContain("librationLongitudeDeg");
    expect(lunarWebglSource).not.toContain("radial-gradient");
    expect(lunarGlobeSource).toContain("prefers-reduced-motion: reduce");
    expect(lunarGlobeSource).toContain("2D ·");
    expect(lunarGlobeSource).toContain('data-render-mode={mode}');
  });

  it("n’ajoute aucun cadre carré ou halo à la sphère lunaire", () => {
    expect(lunarGlobeSource).not.toContain("box-shadow");
    expect(lunarGlobeSource).not.toContain("filter:");
    expect(lunarWebglSource).toContain("gl.clearColor(0, 0, 0, 0)");
  });

  it("présente uniquement la face HMI solaire fixe sur une sphère et identifie tout fallback 2D", () => {
    expect(temporalSunMoonSource).toContain('const sunHeader = <SolarGlobe size="header" />;');
    expect(temporalSunMoonSource).toContain('const sunMarker = <SolarGlobe size="marker" />;');
    expect(temporalSunMoonSource).toContain("face observée uniquement, sans texture globale ni couronne");
    expect(temporalSunMoonSource).toContain("NASA/Goddard Space Flight Center Scientific Visualization Studio");
    expect(temporalSunMoonSource).toContain('href="https://svs.gsfc.nasa.gov/3933/"');
    expect(solarGlobeSource).toContain('prefers-reduced-motion: reduce');
    expect(solarGlobeSource).toContain('loading="lazy"');
    expect(solarGlobeSource).toContain('>2D</span>');
    expect(solarGlobeSource).toContain('data-render-mode={mode}');
    expect(solarWebglSource).toContain("createSolarSphereVertices");
    expect(solarWebglSource).toContain("aPosition.xy * 0.5 + 0.5");
    expect(solarWebglSource).toContain("if (vNormal.z <= 0.0) discard");
    expect(solarWebglSource).not.toContain("uSunDirection");
    expect(solarWebglSource).not.toContain("generateCorona");
  });
});
